### ISSUE TITLE
Change cursor on mouseover for annotation handles

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#1012]
@radpet Currently, the cursor for the handles only change (to rotate and arrows) on mouse down, but they should also change on mouse over so the user knows what the handle does when they move the mouse.

**Comment by radpet** [comment]
@rsinghal That seems logical I agree,  I will send pr with the fix soon

**Comment by radpet** [comment]
https://github.com/IIIF/mirador/pull/1013

**Comment by radpet** [comment]
@rsinghal  I suggest this to stay open until I refactor all the tools in order to handle the mouse over properly :)

**Comment by rsinghal** [comment]
Sounds good

**Comment by radpet** [comment]
@rsinghal  Currently we are using https://github.com/jwarby/jquery-awesome-cursor to show some of the cursors, because there is no build in for rotation, however the browser support for this plugin is bad. What do you think about stopping its usage?

**Comment by rsinghal** [comment]
Yeah, if the browser support isn't great, then we probably shouldn't use it.  It does look like you can point to a specific image using a URL for the cursor CSS, perhaps we could do that instead?  And use the built in cursors for the other handles.

**Comment by radpet** [comment]
Yup I was thinking about this approach :), however I will refactor this after we merge the pull request with the rotation handle as icon (and much more fixes)

**Comment by radpet** [comment]
@rsinghal My next pr will be for this issue. What I am thinking is removing the awesome-cursor lib and use the browser built in cursors.

Just to summarize , correct me if I am wrong somewhere : 

When you 
        mouse over/down shape border the cursor is 'move'
        mouse over/down rotation icon the cursor is 'pointer' 
        mouse over/down resize point the cursor is '*-resize'

[Default cursors example](http://www.w3schools.com/cssref/tryit.asp?filename=trycss_cursor)

**Comment by radpet** [comment]
@rsinghal @beaudet
I hit a wall with the cursor for the resize points. It is okey initially but there is not built in cursor rotate functionality and when you rotate a shape the cursors aren't really helpful (I understand that this point enables me resizing but it looks rather ugly). 

I several ideas to implement this:

1. to draw cursor on canvas then rotate and extract it as image and make the cursor use that image but I don't think it is worthy. Adding complex computation for a thing like cursor.

2. to have a mapping with ranges, for example:
point [0] will have 
'sw-resize' cursor when 0<rotation%360<45 
'e-resize' cursor when 45<rotation%360<90

but I am not sure if it is worthy also.

3. Maybe the easiest solution is to have some custom cursor that shows that this point enables him to resize. This cursor should be such that any rotation does not affect it's meaning (and looks good of course).

Please give your opinion and ideas :)

**Comment by beaudet** [comment]
As per our Skype discussion, a single "pointer" icon would be sufficient (the pointing finger).   If you are feeling fancy, you could implement animation of handle grabbing with the two web kit pointer "grabbers" but that would be gravy.  IE probably doesn't have those grabbers so it would have to fallback to the standard pointer for IE.

**Comment by rsinghal** [comment]
@radpet @beaudet What if you used the move icon when you are not on a specific handle, and the pointer icon when you are on one of the handles?  I think it would be helpful to give a visual clue that the border of the shape does something different than the points.  And since you can only move the shape when you click on the border, I think it should make sense to the end user that that is how you move the entire shape.

**Comment by radpet** [comment]
@rsinghal Yup I agree give me a minute to change it :)

**Comment by beaudet** [comment]
yes, I agree as well.  Although the move icon should probably only appear when the user is hovering in a location where, if they were to click, it would result in a move operation on the shape.  Otherwise, I think the "default" icon should be used.  Is that what you have in mind?

**Comment by rsinghal** [comment]
Yes, that is how @radpet implemented it
