### ISSUE TITLE
Adjust brightness/contrast/saturation options adjust contrast only

### ISSUE THREAD

**Issue by ViktorRibchev** [IIIF/mirador#1017]
Adjust brightness/contrast/saturation options adjust contrast only. 
Each option adjusts the contrast of the image. 

For reference please see how the options work in https://pixlr.com/editor/

**Comment by radpet** [comment]
@rsinghal We have compared them with 
https://pixlr.com/editor/ and they have some major differences. Are those tools fully implemented?
