### ISSUE TITLE
Annotation editor duplicates when used in more than one slot

### ISSUE THREAD

**Issue by radpet** [IIIF/mirador#1032]
The annotation editor dialog duplicates if you don't close it on slot A and open new one for edit on slot B

This is the scenario:

When you create two slots A and B
and:
On A create an annotation and don't save it ( the annotation dialog with the editor should be opened)
On slot B open existing annotation for edit

Then you will see how on slot A there is addition editor field

This issue is presented in both 2.1 and annotation-work

**Comment by rsinghal** [comment]
Fixed in `annotation-work`
