### ISSUE TITLE
2.1 - Confusing UX editing annotation styles

### ISSUE THREAD

**Issue by beaudet** [IIIF/mirador#1066]
After creating an annotation, then selecting edit, the line and fill styles do not seem to be getting applied to the annotations, even after hitting save.  I would expect that after clicking edit and changing the styles, the new styling would be applied immediately (even before hitting save) and then committed if save is selected.    In reviewing this more closely, it appears that the shape has to also be selected in order to apply a new styling which actually does make sense and I understand why you'd need the styling widgets to be active since new shapes can be drawn at this point.  I think if the styling widgets were disabled until using them will actually change something visibly, that would help.  In other words, the styling widgets should be disabled until an existing shape is selected or the user has clicked on a shape icon because they are about to draw a new shape.  Finally, while the color of the shape fill takes effect immediately with the fill widget open, the transparency does not.  I find that to be confusing.  It seems the user has to click out of the widget in order to make the transparency take effect.  It would be better for it to take effect as the slider is moved right and left.

**Comment by rsinghal** [comment]
These are good points - I will take a look at these inconsistencies.

**Comment by rsinghal** [comment]
@beaudet Do you think the border type, border color, and fill color drop downs should disappear when they are not available to the user, or should they simply be "greyed out"?  I'm trying to do the latter, but not sure what color would be sufficient to indicate that it is greyed out when we use a gray color palette! :)

**Comment by beaudet** [comment]
Yeah, good point.  Perhaps "grayed out" could be indicated by a darker gray than the "active" gray or a mask with diagonal slashes could be overlaid on top of the icon.  There are established standards for this type of thing, although I'm not sure they're immediately relevant to a gray palette, e.g. 

https://standards.usa.gov/buttons/  
https://material.google.com/style/icons.html

I suppose if the contrast is significantly reduced for the inactive icons (note that searching for disabled icons gives you recommendations for icons related to disabled persons) and clicking on them does not result in the widget opening, it should be fine.  Ideally, the cursor would change to a circle with a slash through it if that's available.  

I think removal of the icons in this mode is also workable, but conveys less contextual information than making the icons inactive and so it's slightly less desirable.

**Comment by rsinghal** [comment]
@beaudet Take a look at the demo page on projectmirador.org now.  I think I have addressed all of the inconsistencies you noted in this ticket, but if you find anything new, please submit a new ticket.
