### ISSUE TITLE
Saving Annotations: Unclear where Storage is Configured

### ISSUE THREAD

**Issue by schwemmer** [IIIF/mirador#1070]
When I create an annotation and click the "Save" button, nothing happens. As a user I am confused. Should something have happened? Where will my annotation be stored? Why isn't it saved?

From digging through the issues a bit I think I understand that the annotation store is configured when setting up Mirador. I guess this makes sense. But as a user, this is not clear to me. 

I would expect something of the following:

- when no annotation store is configured, clicking the "Save" button should display an error message saying that there is no annotation store configured

- alternatively, the annotation tools should not even be displayed if no annotation store is configured because it is pointless to create annotations that can not be saved (or is it not?)

- instead of configuring the annotation store "globally" for the Mirador instance maybe it would make sense to allow the user to specify an annotation store endpoint when none is configured. Like this, the annotations could be saved on a per manifest basis to external annotation stores

- in any case I would expect some help text somewhere in Mirador that explains how saving/storing annotations work

**Comment by rsinghal** [comment]
Hmmm, I'm surprised that you are seeing the annotation tools when there is no annotation store configured!  That definitely should not be happening.  I will investigate.

**Comment by schwemmer** [comment]
To clarify: I was using this Mirador instance for testing:
http://projectmirador.org/demo/release2_1/

Interestingly, the Stanford "clans of the Scottish Highlands" manifest does not show the annotation tools but the e-codices "Cod. Bodmer 600a" does. 

What's still not clear to me: does the configuration of the annotation store depend on the Mirador instance – so for example for the deme release 2.1 with the link given above it should be the same annotation store for all manifests – or does it depend on information found in the manifest?

**Comment by radpet** [comment]
@schwemmer @rsinghal  Both actually. You may have annotations coming from the manifest. Anyway creating new annotations goes to the endpoint which is configured per Mirador instance.

I see that currently http://projectmirador.org/demo/release2_1/ is using the localStorage as endpoint.
However I found that sometimes you are not able to save annotations and this is probably a bug somewhere.

**Comment by rsinghal** [comment]
If a manifest has AnnotationLists, it will display those annotations by default (see: Ege MS No. 1 - Reconstructed in the demo).  That Mirador demo is saving your annotations to the local storage in your browser.  Mirador is provided information about where to store annotations on configuration of the application.  Currently, only one annotation store is allowed per Mirador instance.

Regarding the differences between the Stanford and e-codices manifests - can you submit screen shots?  As you switch between manifests, Mirador will attempt to open the new manifest using the state you were in for the previous manifests - so if you were annotating before, it will open the annotation tools on load of a new manifest.  But the annotation tools are always available in the demo by clicking on the top left comments icon.

**Comment by sdellis** [comment]
First of all, great work on the ability to save annotations to local storage!  It's a huge step forward for developer and demo use cases, which I believe was the initial intent.  But to support true annotation use cases, I agree with @schwemmer that there should be some feedback to the user as to where the annotations are being saved.  

I doubt it should hold up the release but I would be hesitant to do any real annotation if (unbeknownst to me) all my annotations were being saved to local storage and there was not an easy way to get them out. Perhaps the next step here is some mechanism that can sync local annotations to a remote annotation store (manually or automatically)?

**Comment by rsinghal** [comment]
That is out of the scope of Mirador.  It doesn't really make sense for Mirador to tell the user where the annotations are being saved.  An application that is embedding Mirador can manage that sort of complex information and decide what a user needs to know (for example, in a Harvard course where students are annotating an object for an assignment, they don't care where the annotations are being saved.  That is a part of a larger course application that is using Mirador).

Mirador needs to remain dumb - an application that embeds Mirador can be smarter.  I have no expectation that someone is going to go to that demo page and start doing serious annotations.  If they are, then they are doing so at their own risk.  If a user has a need to do real annotations, then they are going to be doing it within a framework such as what Yale uses for their research projects, and users know that their work is being done within the confines of that framework.

**Comment by schwemmer** [comment]
Thanks to all for clarifying things!

> But the annotation tools are always available in the demo by clicking on the top left comments icon.

> As you switch between manifests, Mirador will attempt to open the new manifest using the state you were in for the previous manifests - so if you were annotating before, it will open the annotation tools on load of a new manifest.

That probably explains why I saw the annotation tool on one manifest but not the other. The notion that Mirador should be "dumb" and an application embedding Mirador could be "smarter" is fine with me. However, as I wrote in my first comment and @radpet confirmed, there seems to be a bug with saving annotations. Saving annotations does not seem to work at all for me. When I click on the "Save" button, nothing happens. When I inspect localStorage, no annotation is stored there and the console shows the following error: 
`mirador.js:46713 Uncaught TypeError: Cannot read property 'data' of undefined`.

This is on Mac OS  El Capitan / Chrome v52. Would you like me to open a separate issue for this?

**Comment by regisrob** [comment]
We also noticed the same bug today while testing annotations ("Cannot read property 'data' of undefined..."), among a few others that I have to write down in tickets or mail before Tuesday!

**Comment by rsinghal** [comment]
Yes, we figured out what the issue is and I will have the demo updated this weekend as well as a new release candidate.

**Comment by schwemmer** [comment]
Great, thanks @rsinghal!
