### ISSUE TITLE
Late additions to index.html

### ISSUE THREAD

**Issue by glenrobson** [IIIF/mirador#1076]
Sorry it took us a long time to reduce the number of items to 10 for inclusion in the list. Completely understand if we're too late for inclusion in the next release but just in case there is an opportunity our selection is available at:

http://dev.llgc.org.uk/iiif/mirador2.1/index.html

and

http://dev.llgc.org.uk/iiif/highlights.json

and includes:

 * Newspaper issue - includes articles with annotation lists which aren't totally working but if it would help I could create a manifest without articles and line OCR annotations.
 * The 'Hengwrt Chaucer' - History of one of the most important surviving texts of the work of Geoffrey Chaucer. 
 * Laws of Hywel Dda - A Latin version of the native Welsh law with a series of illustrations in the text 
 * NLW Drawing volume 299 - colorful sketches of clothing
 * Geoff Charles photographs - Schoolchildren arriving in Newtown and Oswestry from Birkenhead, taking part in air-raid drills and being welcomed at Newtown station .
 * Brogyntyn Lute Book, [c. 1595-1669]  - lute music
 * WW1 Posters - collection of WW1 posters
 * A collection of art works shared as part of the Europeana 280 project
 * Historical Map -﻿ Penbrochiae comitatus olim Demetiae regionis descriptio 1602
 * and my personal favorite 'Cardiganshire Constabulary register of criminals '

feel free to use any or all and sorry for not getting them ready in time for the release.

Thanks

Glen

**Comment by rsinghal** [comment]
This is great!  And not too late - we will get these in before the official release.

**Comment by glenrobson** [comment]
Hi Rashmi,

I noticed Mirador at http://projectmirador.org/demo/ didn't have the extra Wales manifests. Is there a plan to update that site with the new index.html thats in github?

Thanks

Glen

**Comment by rsinghal** [comment]
In order to keep the number of manifests on the demo page more manageable, we decided to limit the number of objects that we display from each institution (in fact, I removed a lot of Harvard objects!).  Are there particular objects you want to add from Wales that I left out?  We are happy to add a couple more.

**Comment by glenrobson** [comment]
Thanks completely understand. I think the three you've chosen for the index.html in Mirador are great. If there is a chance to add one to the projectmirador site it would be nice to have a Newspaper (either one of ours or one of Jason's).

Thanks

Glen
