### ISSUE TITLE
Make annotation body and shape deletion confirmation dialogues consistent.

### ISSUE THREAD

**Issue by sdellis** [IIIF/mirador#1078]
This is a minor usability issue with deleting annotations.  The confirmation dialogue for an annotation asks "Do you want to cancel this annotation?" and the options are "Cancel" and "OK" which could both be seen as confirming/affirming statements.  Simply changing this message to "Do you want to delete this annotation?" (making it consistent with the shape equivalent) would be more clear.  

See the screenshots attached for examples.

![delete-shape](https://cloud.githubusercontent.com/assets/609368/18016483/a1158698-6b9a-11e6-8e04-c7a530c32cf5.png)

![delete-annotation](https://cloud.githubusercontent.com/assets/609368/18016479/99c206c8-6b9a-11e6-9e74-9e9a701805ea.png)

**Comment by radpet** [comment]
@sdellis I agree up to a point, because actually you are not deleting the annotation but you remove the shape that it is attached to it that is why the message was written like that. Do you have ideas how we can improve this?

**Comment by rsinghal** [comment]
What if we switched `OK`and `Cancel` with `Yes` and `No`?

**Comment by sdellis** [comment]
That would work! :)
