### ISSUE TITLE
2.1 - problems with on-shape icons when creating annotations

### ISSUE THREAD

**Issue by beaudet** [IIIF/mirador#1088]
Environment: Windows 7 with latest chrome - Mirador 2.1 demo site - I hit ctrl+F5 to refresh everything but did not manually clear browser cache first.

Problem: click on rotation ignored when creating annotations despite cursor changing to hand on hover

Reproduce:
Create a few square annotations
Select one of the squares you already created
Hover over the rotation icon or the delete icon
Click to rotate or delete
Observe a new shape being created instead rather than rotation mode being activated
Observe that you are creating a shape despite the pointer icon being the active tool

**Comment by radpet** [comment]
There was no such bug before the new candidate release. 
@rsinghal Do you know which change may have caused it?

**Comment by rsinghal** [comment]
Yes, I see this happening as well on Chrome on Mac.  Not sure which commit broke this.
