### ISSUE TITLE
Change the border/fill color of an existing annotation

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#1090]
I did not manage to do this. Is it somehting possible?

_Environment: Mac Book Pro 10.11.5 / Firefox 48.0.1 & Chrome 52.0.2743.116_

**Comment by rsinghal** [comment]
@regisrob For an existing annotation, you would click `Edit` from the text viewer, click on the shape that you want to change, and choose the new color and click `Save`.  If this isn't working for you, can you add your steps to reproduce?

**Comment by regisrob** [comment]
sorry, it works! :confused: 
I just did not understand I had to click on the shape to make the border/background dropdowns active :)
