### ISSUE TITLE
Simple Image Manipulation Requests

### ISSUE THREAD

**Issue by thehabes** [IIIF/mirador#375]
Hi all. I have users that have requested simple 90 degree image rotation as a tool (both positive and negative) for your viewer on a site I am building. There are also request for toggling greyscale and color invert as well as requests for brightness and contrast sliders. I was able to successfully build these requests into the viewer using your coding schema and introduced buttons into the UI.
Do you feel that these bits of functionality are worthy of a pull request?

**Comment by azaroth42** [comment]
Hiyas!  I'm very curious as to how you implemented these :)  Could you give a link to an installed instance to look at? Thanks

**Comment by thehabes** [comment]
I forked the project and have everything on my github you can find the code here: https://github.com/thehabes/m2

Everything I am doing is installed locally and on my work machine and is in the beginning stages, so there is no link I can give you at this moment for testing.  If you take my mirador and build it on your machine, you will see the buttons for rotation in a <div> element with the class mirador-pan-zoom-controls hud-control towards the bottom right corner of whatever SINGLE image is active.  I have not implemented any rotation in the side by side or book view but I am thinking about it.  The changes I made were to hud.js and the mirador.js that came out of building with grunt as well as mirador.css which had to be 'grunted' into mirador-combined.css to take effect.  

Specifically, in mirador.js in bindEvents (line 6617) I added code starting at 6682 and in hud.js I altered the template object on line 203 to add my buttons.  I did the same thing to the object in mirador.js on line 6808.  

If you need something more than what is on my github account, let me know.  I will commit everything now.

**Comment by aeschylus** [comment]
This is exciting. I have cloned your fork and had a look. I see your controls (nice job modifying the h.u.d.), but they don't seem to cause a rotation (not in single mode either).

**Comment by thehabes** [comment]
Ok that is not good.  It is working on my machine.  I can positive and
negative rotate ninety degrees and do 180 degree flips as well.  I have it
working in Chrome and Firefox.  Does it happen to give you an error?

On Fri, Jan 9, 2015 at 11:36 AM, aeschylus <notifications@github.com> wrote:

> This is exciting. I have cloned your fork and had a look. I see your
> controls (nice job modifying the h.u.d.), but they don't seem to cause a
> rotation (not in single mode either).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/m2/issues/375#issuecomment-69368860>.
>



-- 
-------------------------------------------------------------
Bryan J. Haberberger
Web Developer-Center for Digital Humanities
Saint Louis University

"You can say there is no good and no evil, but the fact remains the most
existentially 'good' thing one form of matter can have on another is to aid
in its advancement."
-------------------------------------------------------------

**Comment by azaroth42** [comment]
Is it that you modified the build/ mirador.js directly and thus rebuilding
would overwrite the changes? Or did you put the rotation into a file in the
the src/ directory?

On Fri, Jan 9, 2015 at 9:42 AM, Bryan Haberberger <notifications@github.com>
wrote:

> Ok that is not good. It is working on my machine. I can positive and
> negative rotate ninety degrees and do 180 degree flips as well. I have it
> working in Chrome and Firefox. Does it happen to give you an error?
>
> On Fri, Jan 9, 2015 at 11:36 AM, aeschylus <notifications@github.com>
> wrote:
>
> > This is exciting. I have cloned your fork and had a look. I see your
> > controls (nice job modifying the h.u.d.), but they don't seem to cause a
> > rotation (not in single mode either).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/IIIF/m2/issues/375#issuecomment-69368860>.
> >
>
>
>
> --
> -------------------------------------------------------------
> Bryan J. Haberberger
> Web Developer-Center for Digital Humanities
> Saint Louis University
>
> "You can say there is no good and no evil, but the fact remains the most
> existentially 'good' thing one form of matter can have on another is to
> aid
> in its advancement."
> -------------------------------------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/m2/issues/375#issuecomment-69369746>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by thehabes** [comment]
Yes I modified build/mirador.js directly and thus rebuilding overwrites the changes.  It is not in the src/ directory.

**Comment by aeschylus** [comment]
Ah, okay. If you move that over to the source directory we can build it into the running project. The /build directory should not be versioned/pushed to github. Please see the [wiki contributing guide](https://github.com/IIIF/m2/wiki/Developer-Tooling-and-Workflow#usual-development) or ask here for more help.

**Comment by thehabes** [comment]
OK I will change that up and fix my github and git commits.  Admittedly, I sort of just jumped in without reading directions...sorry about that.  Bare with me while it's messed up at the moment.

**Comment by thehabes** [comment]
I have fixed my commits to ignore the build folder and have moved the mirador.js I am working on into the src/ directory.  I have built and it works just like you said it would.  I am good to go thank you!

I have gotten my filter code to work all the way down to the point at which creating a Filter{} breaks because of the image being "tainted" (which is their way of saying you are trying to alter something grabbed from a different server).  The Filter{} will not alter an image that was taken from an outside source: it must be something local or brought in via a proxy.  The reason I wanted to use this for my other tasks was because Filters{} were created to work with <canvas> elements.  

I am trying an approach just using CSS manipulation next, since for my purposes in my project this will be fine.  At some point in time, I may try a work around with the Filter{} way of doing it.  

Future commits and pull requests to come.

**Comment by azaroth42** [comment]
Thanks Bryan!  I know that Drew is off sick today, but please keep us
informed as to your pure-CSS approach.  The cross-domain issues for IIIF
are definitely pitfalls to keep in mind for developers.  Having a list of
the traps might be a good thing to start accumulating? (@jpstroop @zimeon
@mikeapp)

On Mon, Jan 12, 2015 at 12:33 PM, Bryan Haberberger <
notifications@github.com> wrote:

> I have fixed my commits to ignore the build folder and have moved the
> mirador.js I am working on into the src/ directory. I have built and it
> works just like you said it would. I am good to go thank you!
>
> I have gotten my filter code to work all the way down to the point at
> which creating a Filter{} breaks because of the image being "tainted"
> (which is their way of saying you are trying to alter something grabbed
> from a different server). The Filter{} will not alter an image that was
> taken from an outside source: it must be something local or brought in via
> a proxy. The reason I wanted to use this for my other tasks was because
> Filters{} were created to work with elements.
>
> I am trying an approach just using CSS manipulation next, since for my
> purposes in my project this will be fine. At some point in time, I may try
> a work around with the Filter{} way of doing it.
>
> Future commits and pull requests to come.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/m2/issues/375#issuecomment-69640598>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by aeschylus** [comment]
@thehabes, I left a comment on your most recent commit on your fork earlier today. You need to leave the build file in the build directory and change the appropriate place in one of the source files. 

Mirador uses a build process to take many, smaller, modular files of code (in the `/src` directory) and combines and processes them into a more efficient, minified version of the complete program in the `/build` directory. Looking at your commit, it seems you overwrote the entire (very tiny) `mirador.js` initialisation module in the `/src` directory with the entire complete program. This happens to work because the built file has the same name and contains the code that was in the originally named `/src` file, plus several thousand lines of the rest of the program. 

I'm happy to help you find the particular files you need to edit in the `/src` directory if you want.

**Comment by thehabes** [comment]
I have fixed this.  I did overwrite the tiny mirador.js.  I have restored it to its original code and hooked everything up to commit correctly.  Hopefully the structure is correct if you still see any issues let me know.

I want to keep you updated on what I've done.  I am nearly complete with all the requests that have come to me.

I have implemented an invert toggle and a grayscale toggle (100% on or 0% on).  They work in Firefox and chrome and are untested otherwise.

I have implemented a +90 degree flip and -90 degree flip as well as a 180 degree flip.  They work in FIrefox and Chrome and are otherwise untested.

I have implemented a brightness slider and a contrast slider that go from 0% to 200%.  They work in Chrome but not in Firefox and are otherwise untested.  

To keep things optimally useful, each of these things can be used in combination with any of the others.  There is a button named "normal" that takes off the grayscale and invert filters.  Clicking the filter will toggle it on and off as well.  I will soon have the normal button reset brightness and contrast to the default as well, but for now it does not.  I will make a similar button for rotation so that the user can be assured their image is back to the original location.  

Thats all for now.  Another day or two and I will be ready for a pull request.

**Comment by aeschylus** [comment]
Great Bryan, thanks for taking the time to make these adjustments. I look
forward to seeing how the feature develops. Let us know if we can help in
any way.

**Comment by thehabes** [comment]
I have implemented a full reset so you can undo all the manipulation to the image and return it to the "just loaded up" position.  This means no rotation, no filter and no zoom.  I have made it so that you can hide/show the tools via an arrow you can click.  It slides, nothing special.  It struggles in firefox so it may be worth catching that we are in that browser and making the filtering tools unavailable.  This is one last go through of the code from being a pull request.  I have documented the code I added where necessary.

**Comment by thehabes** [comment]
I cannot get m2 to work at all in IE.

**Comment by aeschylus** [comment]
Interesting. I will look into this today. Which IE are you using?

**Comment by thehabes** [comment]
I am using internet explorer 8, version 8.0.7601.17514 and trying to run off my local machine.  The grunt build is successful and I am running it off an apache tomcat instance which starts up with no errors.  The same build works fine in Chrome and Firefox off the tomcat localhost server.  I traced the error down to slotObjects, and when slotObjects attempts to be defined it never happens and breaks on the line 
return slotObjects;

**Comment by thehabes** [comment]
I just tested it with the master instance and got the same error....I haven't tested it outside of windows 7 using internet explorer 8 version 8.0.7601.17514.

**Comment by azaroth42** [comment]
Would be good to split this to a separate issue for tracking please

**Comment by thehabes** [comment]
done!

**Comment by sdellis** [comment]
@thehabes Are your rotation changes in a public branch somewhere?  I'm curious as to whether it's based on using the OSD setRotation() method.  I've been having issues with the cropping of images in the viewport when using setRotation, but perhaps you've taken another approach that gets around the problem?

**Comment by thehabes** [comment]
All of my code is on my github here: https://github.com/thehabes/m2 and is open to the public.  Feel free to fork, clone and/or take apart.

I did use the setRotation method.  Cropping an image is an interesting issue.  If you did it trying to alter the OSD object then changing the size of the canvas element or container or parent container (etc.) will automatically resize the image thus discouraging the UI from successfully cropping.  My tools avoid interacting with the image and only interact with the container(s) around the canvas element.  

I have designed crop tools on the IIIF canvas before in other projects.  I will keep an eye on what you are doing.
In my opinion (which could be totally useless) your best bet may be place another Div element inside the OSD container that will mask the canvas and only show whatever piece of the image size and location coordinates the cropping provides.  Trying to do something similar to the OSD canvas and containers will not work.  Sort of like how the annotations work, except show the overflow and make the background a solid color and have it size to 100% x 100% the canvas (or container) height and width.  Then rotation will not be a factor as whatever cropping you do will rotate with the OSD container.

**Comment by sdellis** [comment]
Ok, thanks for the link!  Yes, I think it's a bit more complicated and seems to be a deeper level OSD issue.  I'm working through a [bug ticket](https://github.com/openseadragon/openseadragon/issues/567) and am trying to get my head around it.  [My use case](http://libphp-prod.princeton.edu/versailles/item/842) is to compensate for images that were not properly oriented to begin with.  The show needs to be announced soon, so if I can't tackle it in the next day or so, I'm probably just going to have to write a shell script that uses ImageMagick to orient them properly on the server for now.

**Comment by thehabes** [comment]
I know everyone is working hard for your 3/20 release, but I believe I have finalized my code and would do a pull request if the code is wanted.  The wiki says to get approval through an issue before making the request, so I am officially asking for approval.  If there is no time to review the code to decide whether you want it as is, then I will wait to bring it up again until after the 2.0 release.  Happy coding!

**Comment by rsinghal** [comment]
I took a look at your fork, and it is looking really nice.  I think we can integrate this into the 2.1 release.  We plan to change some of the canvas controls anyway, so this will feed into that nicely.  I did notice that if you use either of the sliders and click on Reset All, it doesn't reset the location of the slider.

**Comment by thehabes** [comment]
Thanks for taking a look!  I did not notice that problem but you are correct, I will fix that.  I didn't want to bother anyone with this until 2.0 is released so I will worry about the pull request sometime next week.  I will fix the bug you gave me and look for any others.

**Comment by thehabes** [comment]
I have implemented bug fixes for the sliders resetting.  They now reset on next() and previous() and the reset all function.  I have fixed the tool tips and got it working in book view mode.  This should be ready to merge.

**Comment by jabrah** [comment]
I have been looking a bit into image rotation in Mirador. A use case for my project involves viewing interesting bits of an image near the edges, so the image cropping brought up in this thread is a big deal for me. As Shaun had said, this is an issue deep in OpenSeadragon which is still unresolved.

There is a work around that will get around the OSD bug with image rotation. For now, it is possible to change the `visibilityRatio` setting on OSD to a number less than 1. This will eliminate the unwanted image cropping on images rotated at 90 or 270 degrees. However, it comes at a cost of part of the image viewing experience of unrotated images, or images rotated at 180degrees. For these cases, the edges of the images will no longer snap to the edges of the viewport as it does currently, instead, it will 'snap' to somewhere in the middle of the viewport.

The relevant OSD setting inside Mirador:
https://github.com/IIIF/mirador/blob/master/js/src/utils/openSeadragon.js#L9

As a workaround, changing this to 0.68 will be sufficient. Below is a link to a demo with the modified setting to show the OSD behavior in Mirador. Be aware that this is not a permanent link, so it may go down.

http://rosetest.library.jhu.edu/mirador-rotation-workaround

**Comment by nicolasfranck** [comment]
I've tried the branch release2.1 but that does not not have these image manipulation tools. The fork https://github.com/thehabes/m2 is also gone. Any idea where these changes are?

**Comment by thehabes** [comment]
Sorry about this.  My fork had too much going on to do pull requests, so I ripped it all down and planned on putting it all back bit by bit so I could do modular pull requests, but then I had NPM problems so I was halted.  You are not the first to come looking for it.  

I have integrated all my code with the release2.1 code.  You will find this code at https://github.com/thehabes/mirador in the branch release2.1.  At this moment, the tools are not there.  I will put them in today and contact you when they are up @noclasfranck

**Comment by nicolasfranck** [comment]
Thanks. I'm looking forward!

**Comment by aeschylus** [comment]
Rashmi will be demo-ing integration of the image manipulation tools tomorrow on the Mirador Community call. You should join us if you like. For the details, subscribe to the [mailing list](https://groups.google.com/forum/#!forum/mirador-tech), or visit [gitter](https://gitter.im/IIIF/mirador). We will also put out a brief progress announcement on 2.1 (including image manipulation) after the call tomorrow.

**Comment by aeschylus** [comment]
@rsinghal

**Comment by thehabes** [comment]
I have put the version of Mirador with all of the changes up in another repo at https://github.com/thehabes/mirador_twig if you want to look at code now. I cannot put it with this fork or it will mess up my PRs (sorry about that @aeschylus )!  I will be making all the code in that twig into code I can make into PRs piece by piece and with time and some guidance so I don't muddy up the IIIF/Mirador repo.  @nicolasfranck if you need more let me or the group know.

**Comment by aeschylus** [comment]
Github provides a good interface for managing branches for PRs. You can make a PR from your fork's branch. I found this handy guide:

https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository

**Comment by thehabes** [comment]
Thank you, that was certainly helpful I should have made branches from the original release2.1 from the beginning for each piece, that makes PRs way easier. I think I did it right this time. See PR #992 and the img-manipulation-tool branch of the thehabes/mirador fork for that piece of development from my end...and any other tips are greatly appreciated :+1:
