### ISSUE TITLE
Synchronous XMLHTTPRequest deprecated in chrome.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#388]
Newest chrome has deprecated all synchronous ajax requests (for good reason). Mirador is now complaining about them. We shouldn't have any of these anyway, so we'll see where they're hiding. Find them and destroy them.

**Comment by pobocks** [comment]
Hello, this is Dave from LTS - I'm working on familiarizing myself with the code base, and am doing so partly through picking off low-hanging fruit from the issue queue. Feel free to ignore the PR if it's not useful/duplicates effort.

**Comment by aeschylus** [comment]
Thanks for the contribution. I will pull it down and have a look. The diff looks pretty straightforward. 

If you're looking to familiarise yourself with the codebase, a great place to start is with the [`mirador.js`](https://github.com/IIIF/m2/blob/master/js/src/mirador.js) file. That is our entry point (fired off when the page loads/`Mirador({...})` is called. Everything spiders down from there.

Most of our requests are done using [promises/deferred](http://www.danieldemmel.me/blog/2013/03/22/an-introduction-to-jquery-deferred-slash-promise/), but not all of them have been migrated to that pattern.

Thanks for your interest!

**Comment by pobocks** [comment]
I left getJsonFromUrl and its tests around because I think there's an issue with the tests which could show up in other places.  I'm writing an issue for that, and will reference this PR there.

**Comment by rsinghal** [comment]
At least one culprit is i18next.  We force the resource file to load asynchronously or the translations won't be fully loaded before the dom elements are populated.  Doing #935 should give us the option to handle the loading of the resource file differently, using one of these backends: http://i18next.com/docs/ecosystem/#plugins

**Comment by aeschylus** [comment]
My pr fixed that. https://github.com/IIIF/mirador/pull/920

Do you want to re-open and I can merge your approach to the dev/GB issue, then we can integrate it into 2.1?

**Comment by rsinghal** [comment]
I didn't realize you had also changed viewer.js - thought you just added the new files.  I think you already merged my PR with the extra settings, so I'm just going to submit a new PR with your changes to viewer.js.
