### ISSUE TITLE
Rename BnF logo

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#407]
If it's still relevant for you (pending "Phase 2: The load window should use .logo from the manifest"): 
- rename to "bnf_logo.jpeg" to follow common pattern
- rectify the pattern given in https://github.com/IIIF/m2/wiki/Short-term-Logo-Addition ("[institution]-logo.[png|jpeg]")

**Comment by aeschylus** [comment]
We will cover this today.

**Comment by aeschylus** [comment]
This was closed a while ago, but never got actually closed.
