### ISSUE TITLE
metadataView: linking fields do not support object or list of objects

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#414]
Mirador seems to only supports strings in related/seeAlso/within fields.

For example:
<pre>
"related":{
    "@id": "http://example.org"
}
</pre>
will print "@id: http://example.org" in metadata view

and:
<pre>
related: [
  {
      "@id": "http://example.org"
  },
  {
      "@id": "http://example2.org"
  }
]
</pre>
will print:
[
@id: http://example.org
,
@id: http://example2.org
]

Presentation API says "A label and the format of the related resource should be given to assist clients in rendering the resource to the user": http://iiif.io/api/presentation/2.0/#linking-properties
Question (cc @azaroth42): How it is supposed to be written in JSON-LD?

The complete example in the spec gives:
<pre>
"related":{
    "@id": "http://www.example.org/videos/video-book1.mpg",
    "format": "video/mpeg"
}
</pre>

But if I want a label as recommended in the spec, is it allowed to write?:
<pre>
"related":{
    "@id": "http://www.example.org/videos/video-book1.mpg",
    "format": "video/mpeg",
    "label": "A video about Book 1"
}
</pre>

If so, I guess the expected rendering in Mirador would be:
Related:    [A video about Book 1](http://www.example.org/videos/video-book1.mpg)
(with an optional tooltip or icon, depending on the value of "format")

... or if there are two links: 
Related:&nbsp;&nbsp;[A video about Book 1](http://www.example.org/videos/video-book1.mpg)<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Catalogue record](http://www.example.org/record/12345)

Is it the expected display? And is it correct with respect to the spec?

**Comment by azaroth42** [comment]
That is the correct JSON-LD :)

**Comment by regisrob** [comment]
Ok, so if it's correct I will use that syntax in our Gallica manifests (for the links to the catalogue records). 
The stringifyObject function will need some refinements ([metadataView.js#53](https://github.com/IIIF/m2/blob/master/js/src/widgets/metadataView.js#L53)). I'll try to work on this ASAP.
Thx

**Comment by mikeapp** [comment]
Ignore the reference above, it would impact other values with an @id and profile, such as a logo image specified via IIIF.

**Comment by rsinghal** [comment]
@regisrob Do you happen to have some example manifests that I can test against?

**Comment by regisrob** [comment]
I think it's fine now, fixed by 4949173567a04ef319f30e4ccf4a809cda13b124. 
I've just tested with this manifest: http://iiif.biblissima.fr/manifests/ark:/12148/btv1b8529692z/manifest.json
The label display seems to be ok too, e.g. when you have a label field inside "related":
<img width="588" alt="capture d ecran 2015-12-04 a 10 23 15" src="https://cloud.githubusercontent.com/assets/402117/11586111/16c70e62-9a71-11e5-8fe0-7e1ace9e21c2.png">
