### ISSUE TITLE
Mirador build issue - incorrect paths for fonts and logos

### ISSUE THREAD

**Issue by pobocks** [IIIF/mirador#435]
When I run `grunt`, the `mirador-combined.min.css` produced has an incorrect path for Fontawesome. 

Instead of `../fonts/fontawesome-whatever`, I get `../font/fontawesome-whatever`.  This only shows up in the minified CSS - non-minified seems correct.  I've verified this on my local machine (OSX), and on a CentOS VM. 

Not sure what is causing this - I've been investigating upward into grunt-contrib-cssmin and cleancss.  The `rebase: false` and `cleancss: false` options don't make a difference.

**Comment by aeschylus** [comment]
Hi @pobocks, I have been unable to reproduce this in a fresh build. Which ref/hash were you building from?

**Comment by pobocks** [comment]
Still happening on tip of master as of this morning.

**Comment by rsinghal** [comment]
@pobocks This is (actually) fixed in `release2.1`.  Please re-open if it isn't.

**Comment by pobocks** [comment]
Ooooh! I'm sick home, but I'll test this Monday! Thanks!

**Comment by pobocks** [comment]
I got antsy - definitely fixed!
