### ISSUE TITLE
BUG: ScrollTo behavior on TOC behaves unpredictably 

### ISSUE THREAD

**Issue by pobocks** [IIIF/mirador#499]
The "spring to open element" behavior attached to the TOC has some serious usability issues.

The "spring to currently active heading" functionality is way too easily triggered by accident.  One px of movement outside the bar to the right while or between interacting with the scrollbar and clicking an element, and scroll triggers.  Personally hit this multiple times before figuring it out. If the user's hand slips to the right or past the TOC while scrolling up or down (very common), this results in the extremely frustrating pattern of:

1. Grab thumb and scroll.
2. Move mouse to click target.
3. Target rockets out of view.

At a minimum, the mouseleave handler needs to be disabled completely during and immediately after scrollbar manipulation.

Even if this is fixed, the mouseover-controlled TOC movement is still not discoverable, and seems likely to violate user expectations.  The delayed mouseleave handler, in particular, startled me.  Example use case that this breaks:

1. User sees reference in page content to content on another page (e.g. endnote, page reference, etc.)
2. User goes to toc, scrolls to general region of interest.
3. User forgets exact reference, or finds that he needs more specific information that's inside window
4. User manipulates window to get this information
5. While user is manipulating window, TOC jumps to wherever they started

My personal solution would be to remove the scroll-on-mouseover behavior entirely, and only change TOC interface state on clicks that select a different image or direct clicks on the TOC.  A "center TOC on focused image" control would provide the functionality in a way that left users in control of the interface.

**Comment by aeschylus** [comment]
This is known. I agree it should probably be removed until such time as the interface can be rationalised. The TOC is intended to behave like a "mini-map" representation of the image collection/book/manifest. As the user moves through the text with next-previous, or uses the bottom panel, the different areas should reflect the change. However, it is hardly fully-realised, so the time-delay behaviour should be removed for now.

**Comment by pobocks** [comment]
Made a PR for this, because why not spare you guys some typing ;-) Just took out the mouse-enter/mouse-leave functionality, haven't made the explicit "focus on selected item" control. mentioned above.

**Comment by rsinghal** [comment]
Not closed, but can be made better in the future, rather than completely removing.
