### ISSUE TITLE
Display issues in metadata panel

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#519]
Floats are not properly cleared in "metadata-listing" definition list. It appears when the last label breaks in two lines, and it raises the following bugs:

* The "sub-title" of the following section is not aligned properly (see "Rights"): 
![selection_005](https://cloud.githubusercontent.com/assets/402117/7133997/ed1f3afc-e298-11e4-8e4c-e125e11e9c2a.png)

* Or the margin between the next section is not properly set:
![selection_004](https://cloud.githubusercontent.com/assets/402117/7134001/f29beb1a-e298-11e4-9b18-e17cb2a67bfd.png)

This widespread clearing method does the trick:
<pre>
.mirador-viewer dl.metadata-listing:after {
content: "";
display: table;
clear: both;
}
</pre>

There is another bug that is quite embarrasing because it affects the proper reading of the metadata (label/value pairs are not aligned with each other when there are multiple labels breaking in two lines):
![selection_003](https://cloud.githubusercontent.com/assets/402117/7134314/09454fde-e29c-11e4-9aee-938052f6e162.png)

**Suggestion: would it be better to have divs instead of definition lists and apply a tabular layout with css?**
The markup could be:
```
<div class="metadata-listing">
  <div class="row">
    <div class="label cell">Label:</div><div class="value cell">Value:</div>
  </div>
</div>
```

**Comment by regisrob** [comment]
If you validate the suggestion (and because it's very easy) I could make my first PR :wink:

**Comment by rsinghal** [comment]
That seems reasonable to me.  Please feel free to submit a PR.  Can you also include the manifest URI that is creating these display issues with the PR?

**Comment by aeschylus** [comment]
Sounds reasonable to me. In general we're due for a re-css-ification, _à la_ #365 and #104, but have at it!
