### ISSUE TITLE
Add window specific settings that can also be global

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#532]
These settings should then affect every window in the workspace.  Add more to this list:
- [ ] Turn off annotation layer for all windows

**Comment by aeschylus** [comment]
Is this closed then? I think so. @rsinghal please re-open if not.

**Comment by rsinghal** [comment]
Not implemented yet

**Comment by rsinghal** [comment]
To describe this in greater detail - the idea is that right now, we can only describe specific window settings within the `windowObjects` setting.  But, they only take effect if the `windowObjects` item points to a specific manifest, which means the developer must configure Mirador to open on a specific manifest and those settings only apply to _that_ slot.  If a user opens a new slot and closes the old slot, those settings disappear.  So, the idea is to make the window settings applicable to all windows and allow a developer to be even more specific on a per-window basis.
