### ISSUE TITLE
Support drag and drop of IIIF resources into empty slot

### ISSUE THREAD

**Issue by snydman** [IIIF/mirador#536]
As a user, if I find a IIIF resource in my discovery system, I want to be able to drag a thumb of that resource to an empty mirador slot such that it allows me to view the object in that slot, and the object is made available to me in the Mirador load window.

**Comment by rsinghal** [comment]
@mikeapp

**Comment by aeschylus** [comment]
See: http://zimeon.github.io/iiif-dragndrop/

#656, #655
