### ISSUE TITLE
Mirador does not have an obvious LICENSE file

### ISSUE THREAD

**Issue by azaroth42** [IIIF/mirador#544]
... and it should to enable developers to know what can and can't be done with it.

For example SLU's "we don't want to share our broken books code" would be incompatible with any share-alike/gpl style license, so clarification early would be good.

**Comment by blalbrit** [comment]
Interesting - M1 had: https://github.com/IIIF/m1/blob/master/LICENSE.md Was there a decision not to port that over, or just an oversight?

**Comment by aeschylus** [comment]
An oversight. I'll port it over now.
