### ISSUE TITLE
Display of overlapping annotation regions

### ISSUE THREAD

**Issue by snydman** [IIIF/mirador#550]
From Jeffrey Witt https://www.youtube.com/watch?v=HoG6W7f_GuA

More coming from Sean Martin coming....

**Comment by snydman** [comment]
@rsinghal @aeschylus Is this a bug or pushing the limits of current implementation?

**Comment by rsinghal** [comment]
There is no sorting implemented. We should be able to sort them by top left position, but there also needs to be logic, then, to sort them by top right position if it's a r-to-l object or if the annotations are in a r-to-l language, etc.  It can very easily get complicated.  But the hovering was never meant to be a great representation for transcription annotations, so really there needs to be different ways of viewing these types of annotations.

**Comment by blalbrit** [comment]
Having just done a bunch of annotations for Sean and co. for their pilot, the hover is also not working well for more complicated "commenting" annotations - so it's not just transcriptions that are impacted. 

Their use case has multiple layers of overlapping commentary annotations - some with quite long commentary - and the hover overlap display makes it very difficult, from a user perspective, to determine the content of the specific annotation being viewed/clicked/zoomed.

**Comment by rsinghal** [comment]
Correct, this was very much a first pass at making annotations visible in Mirador.  We need use cases and designs for other annotation views before they can be implemented.
