### ISSUE TITLE
bookmark feature is not providing a bookmark url.

### ISSUE THREAD

**Issue by jeffreycwitt** [IIIF/mirador#559]
![screen shot 2015-06-12 at 3 40 36 pm](https://cloud.githubusercontent.com/assets/1146685/8138507/76644d08-1119-11e5-9453-6de888df5342.png)

I'm nor sure when this started happening, but I don't think it was also erring in this way. In any case at the present, if I as for a bookmark-able url, I end up with just a blank input field as seen n the screen shot. Included the console so that you could see various errors in case they are related.

**Comment by azaroth42** [comment]
:+1: I noticed this on projectmirador demo this week too. Thankfully before trying to demo it at OR2015.

One of the pitfalls of relying on external services, I imagine.

**Comment by hashimmm** [comment]
The bookmark URL does appear if objects are added to the slots and then I try to bookmark. In that case the copy-to-clipboard link does not work, though.

**Comment by jeffreycwitt** [comment]
Bookmark URL was appearing today, but the link wasn't taking the user back to the desired workspace view. 

In other words, I created a workspace, copied the url from the bookmark panel, and then pasted that link into my blog. But then, when I clicked on the links from the blog, it did not take me back to the desired view. It was usually just a blank mirador view, but sometimes the wrong manuscript. Not sure what the issue is but it seems a bit critical because it is hard to share the magic of IIIF if we can't direct a user to the workspaces we've created.

**Comment by aeschylus** [comment]
Yes, JSONBlob is a problem and must be expunged. There is a [pull request](https://github.com/IIIF/mirador/pull/565) for this, but I need to review it. 

Regardless, a small backend service will be needed to store the link information. Currently the state is stored in localStorage and simultaneously in the remote JSONBlob Store, which simple maps a complete snapshot configuration data to a url identifier. The reason this may fail is that the request to send the most recent update may have failed. 

We have begun to discuss how to best support sharing (with an without a backend) in issue #490. The question is, what interaction do people want and what exactly will they expect. 

Some people want a single url that gets updated with the most recent version of the configuration, others want a unique url for every unique state of the application, others want all the configuration to be included in the url bar as query parameters (not semantic and likely not possible across browsers as this requires quite a bit of configuration data to be stored there, and much of it is nested).

**Comment by aeschylus** [comment]
Regardless, we need to write some tests for this.

**Comment by rsinghal** [comment]
Closing this out because the bookmark endpoint is now pluggable.  For a lack of a better alternative, Mirador main will still ship with JSONBlob but better documentation about the bookmarking feature will hopefully help with things in the future.
