### ISSUE TITLE
Institutional logos are covered by Apache2 Licence

### ISSUE THREAD

**Issue by azaroth42** [IIIF/mirador#563]
I assert that the license file asserts the Apache2 license over all content in the repository. The repository includes the institutional logos of the BNF, Yale, Stanford, NLW, Harvard, e-codices.  That license allows me to use, sell, distribute and modify those logos however I wish. I imagine that our respective general counsels would be MOST UNHAPPY about that. 

I suggest that as our highest priority, we implement the correct fix for the logos, which is to use the logo image associated in the manifest, and delete all but the IIIF logo from the repository.

/fao @regisrob @mikeapp @rsinghal @glenrobson @tcramer @snydman

**Comment by rsinghal** [comment]
PR #533 needs to be slightly tweaked, as it is looking at the wrong image in the manifest, but that can be implemented quickly.  The bigger issue is only BnF and (soon) Harvard objects have the logo in the manifest - I still need to refresh all of the Harvard manifests so they actually include that information.  Hopefully some other institutions can add their logos as well so we don't have an overload of the IIIF logo when demoing Mirador.

**Comment by azaroth42** [comment]
@rsinghal Totally agreed (and why I tagged a bunch of people, and will email Raphael directly). Stanford will need to re-publish all of our manifests to make the change :(

**Comment by blalbrit** [comment]
@azaroth42 Rob, let me know what's required here. Is the goal to point to an institutional logo from within the manifest? We'll need to change the way our IIIF manifest-creator service works, and then republish thousands of manifests. I'll need to schedule that work.

**Comment by azaroth42** [comment]
Yep. Set the logo in the manifests (per
http://iiif.io/api/presentation/2.0/#rights-and-licensing-properties)
rather than having them hard coded in the client.  The code change is
likely one line. The republishing is the more costly part. It does solve
two issues -- the licensing one, and having to collect everyone's logos and
assign them a name.

**Comment by blalbrit** [comment]
@azaroth42 Great, makes sense. Agreed the code change is easy - adding logo to repository now so we have a IIIF URL to point to.

**Comment by regisrob** [comment]
:thumbsup:
Our Gallica manifests already have the "logo" property and all the manifests produced in the framework of Biblissima in the next months will have it too (BnF and IRHT)

**Comment by rsinghal** [comment]
Fixed with #533.  Let's get institutions to add logos to their manifests!!

**Comment by azaroth42** [comment]
Hooray! Many thanks @rsinghal (and all)

**Comment by glenrobson** [comment]
Is anyone using a IIIF enabled logo? If so should it look as follows:

```
"logo": {
        "@id": "http://dams.llgc.org.uk/iiif/2.0/image/logo/full/,150/0/native.jpg",
        "service": {
            "@context": "http://iiif.io/api/image/2/context.json",
            "profile": "http://iiif.io/api/image/2/level1.json",
            "@id": "http://dams.llgc.org.uk/iiif/2.0/image/logo"
        }
    }
```

Cheers

Glen

**Comment by blalbrit** [comment]
Hi Glen, 

That's really close to what we will have: 

' logo ' => { 
	' @id ' => " http://stacks.stanford.edu/image/iiif/wy534zh7137%2FSULAIR_rosette/full/400,/0/default.jpg " , 
	' service ' => { 
	' @context ' => " http://iiif.io/api/image/2/context.json " , 
	' @id ' => " http://stacks.stanford.edu/image/iiif/wy534zh7137%2FSULAIR_rosette " , 
	' profile ' => " http://iiif.io/api/image/2/level1.json " 
	} 
	}, 
The one difference being that we followed the canonical URI structure specified in the image API: http://iiif.io/api/image/2.0/#canonical-uri-syntax which puts w, for a size specification instead of ,h . 

Best, 

B. 

Benjamin L. Albritton 
Digital Manuscripts Program Manager & 
Accessioning Services Manager 
DLSS, Stanford University Libraries 
Stanford, CA 94305-6004 
Phone 650.454.4164 


----- Original Message -----

**Comment by glenrobson** [comment]
Thanks Ben, Ill copy that.

Cheers

Glen
