### ISSUE TITLE
Annotation Icon displayed regardless of settings.

### ISSUE THREAD

**Issue by pobocks** [IIIF/mirador#566]
So far, as far as I can tell, there is no way to disable the annotation icon via config, despite several settings which appear likely to do that. 

The control is question is the chat bubble icon in lower-left of the HUD, with CSS classes `mirador-osd-annotations-layer hud-control`, defined in handlebars template [here](https://github.com/IIIF/mirador/blob/39fc4b03e9ca65e361a47e18b6a0148b4c22274a/js/src/widgets/hud.js#L233).

So far, I've tried setting annotationLayer(Available?) false in the following places:
* options -> defaultWindowSettings
* options -> workspaces -> (singleObject|compare|bookReading) 

Neither setting has had an effect in either place.  Additionally, defaultWindowSettings appears to be set once, then never actually used as a default anywhere, although I could be missing something.

At this point, despite having no annotation source defined, and every annotation-related setting I can find in settings.js set to false, I still have the button.

**Comment by aeschylus** [comment]
You are correct about defaultWindow settings. We haven't integrated that layer of settings yet, but that is an issue that needs to be addressed.

See #569 

The underlying way these interact with the canvas is changing significantly in the current osd-collections branch, but it might be worth fixing in master in the meantime. 

It might help to know that there's a "check" being done at [40-44 in hud.js](https://github.com/IIIF/mirador/blob/master/js/src/widgets/hud.js#L40-L44). This is in the style of an "[immediate mode GUI](http://sol.gfxile.net/imgui/)"(IMGUI). In general I would like to avoid this or at least harmonise the strategy used to implement this kind of option toggling. The "IMGUI" strategy only really works if there is a single central event bus or rendering bottleneck, as in a game using an animation loop. This is true for Mirador in some areas but not others.

A quick fix for the annotation icon displaying inappropriately is to add another "check" to the hud, but this would be rather brittle, and our decision to use this "IMGUI" has caused some bugs in the past when we have needed to duplicate such checks.

Other places we use a state machine, others we use something similar to a one-way data flow, similar to Backbone.js, where an object updates its data representation and the template is re-rendered or transitioned to that state. Places where d3 is used force this to be the case. One strategy will not apply in every situation, but it would be nice to re-evaluate how the UI is represented as data, and have greater unity in the approaches used to render, update, and synchronise multiple views of it.

**Comment by aeschylus** [comment]
One of the best presentations of the last strategy is in "[Representing UI State as Data](http://nicolashery.com/describing-ui-state-with-data/)" by Nicholas Hery.

**Comment by rsinghal** [comment]
annotationLayer works within the windowObjects section of the settings.  You set it for a particular window that is being opened through the config.

**Comment by rsinghal** [comment]
This is subsumed by #532.  Let's move all relevant information there.
