### ISSUE TITLE
Mirador issues requests for images via HTTP when HTTPS is specified in the manifest

### ISSUE THREAD

**Issue by jbhoward-dublin** [IIIF/mirador#576]
We've been transitioning web services to https. When we closed port 80 on the server hosting our loris installation an issue with Mirador emerged: it made requests for thumbnail images via https, but requests for larger images were made via http and we accordingly not completed. We've addressed by re-opening port 80 but would ideally like to see the behaviour changed in Mirador. A sample manifest where this behaviour was seen can be found here: http://data.ucd.ie/api/img/manifests/ucdlib:36572.

**Comment by rsinghal** [comment]
Your info.json has an http ID:
https://iiif.ucd.ie/loris/ucdlib:36777/info.json.  Image requests are created from that ID.

Update that to point to https and Mirador will make the correct requests.

**Comment by edsu** [comment]
I think I'm seeing similar behavior with this simple test:

https://edsu.github.io/mirador-test

manifest is here:

https://edsu.github.io/mirador-test/manifest.json

**Comment by edsu** [comment]
It turned out to be a problem with using https://edsu.github.com/mirador-test/manifest.json instead https://edsu.github.io/mirador-test/manifest.json in my viewer config. https requests to edsu.github.com get redirected to http edsu.github.io ... :-)
