### ISSUE TITLE
Custom user logo through configuration options

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#582]
It should be possible to add a custom logo without any text, i.e. the label in "userLogo" option should not be mandatory (https://github.com/IIIF/mirador/blob/master/js/src/viewer/mainMenu.js#L150). So that we could only have...: 
```
"userLogo": {
   "iconClass": "iiif",
   "attributes": {"href": "http://iiif.io", "title": "IIIF"}
}
```
which outputs:
```
<a href="http://iiif.io" title="IIIF"><span class="iiif"></span> </a>
```

... and then add the logo with CSS.

@aeschylus @pobocks: Or would it be better to have a separate function for the logo? => i.e. a new function processUserLogo() only for logo insertion (inside a Div instead of an html list), and keep processUserBtn() for other custom links/menus

**Comment by pobocks** [comment]
I think that would be a bad move from an accessibility standpoint - screen
readers aren't guaranteed to read the title attribute.

IMHO, the right thing to do is to include link text, and then hide it with
CSS using negative text-indent or similar.

**Comment by regisrob** [comment]
text-indent is obvious, forgot about it momentarily :grin:
Will do this way
Thx

**Comment by regisrob** [comment]
Can be closed of course
