### ISSUE TITLE
Disabling bookmark/layout buttons removes the entire main menu bar

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#597]
When bookmark and layout buttons are both set to false in config options, the main top bar does not show even if "userLogo" or "userButtons" are properly set in "mainMenuSettings" object.

**Comment by aeschylus** [comment]
Likely css related.

**Comment by regisrob** [comment]
I believed it was in the javascript... here: https://github.com/IIIF/mirador/blob/master/js/src/viewer.js#L54 (in this code, "showMainMenu" remains false even if there is a "mainMenuSettings.userLogo", correct ?)

**Comment by aeschylus** [comment]
Ah, yep, that's it. We'll have to make sure any configuration-added buttons are present as well.
