### ISSUE TITLE
Stop calling Mirador a IIIF "reference implementation"

### ISSUE THREAD

**Issue by azaroth42** [IIIF/mirador#600]
Because it's not, and there's (apparently) no will to make it one. Imagine all of these words linked to multi-year outstanding issues.  And then these words to issues being actively worked on that fall outside of the specifications.

This is what reference implementation means:
  https://en.wikipedia.org/wiki/Reference_implementation

**Comment by azaroth42** [comment]
(Point made)

**Comment by jpstroop** [comment]
:+1:
