### ISSUE TITLE
Add images for Wiki and README

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#604]
Any images left in the issues are given an automatic URL by github. This url can then be used within the documentation of the repository, as [described here](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/). Since I find it inconsistent that I can easily drag in resources to the issues editor, but not in the documentation, and because I don't want to host random images for this repository in yet another image host, I will be leaving any images needed here. Feel free to add diagrams, screenshots, or GIFs that might help document the use and structure of Mirador.

**Comment by aeschylus** [comment]
<img width="1381" alt="screen shot 2015-08-01 at 21 21 05" src="https://cloud.githubusercontent.com/assets/145874/9024728/1c2aa308-3894-11e5-9f7f-e9af615df3ba.png">

**Comment by aeschylus** [comment]
<img width="1385" alt="screen shot 2015-08-01 at 21 54 01" src="https://cloud.githubusercontent.com/assets/145874/9024775/eb475138-3897-11e5-85f0-e778c496395e.png">

**Comment by aeschylus** [comment]
<img width="1383" alt="screen shot 2015-08-01 at 22 36 26" src="https://cloud.githubusercontent.com/assets/145874/9024882/de8af50c-389d-11e5-822a-9d049e1abce5.png">

**Comment by aeschylus** [comment]
![transcription panel to the right](https://cloud.githubusercontent.com/assets/145874/9209693/bdbfff3e-402c-11e5-9628-655666c570ee.png)
![transcription panel on the bottom](https://cloud.githubusercontent.com/assets/145874/9209694/bdc33302-402c-11e5-8ddc-46dd0292588f.png)
![reading with everything](https://cloud.githubusercontent.com/assets/145874/9209695/bdc34aa4-402c-11e5-9050-743029c9501a.png)

**Comment by rsinghal** [comment]
![annotationstatemachine](https://cloud.githubusercontent.com/assets/2371632/10643639/e3fb9dfa-77f1-11e5-8b34-f04c055417df.png)

**Comment by rsinghal** [comment]
<img width="1355" alt="screen shot 2015-10-21 at 3 33 50 pm" src="https://cloud.githubusercontent.com/assets/2371632/10647890/3ece96f8-7809-11e5-9ac9-c0a9f76685eb.png">

**Comment by rsinghal** [comment]
![drag_and_drop](https://cloud.githubusercontent.com/assets/2371632/10648186/fe55be06-780a-11e5-9cdc-766533902602.gif)

**Comment by aeschylus** [comment]
These seem helpful. Where are they being added? :)

**Comment by rsinghal** [comment]
Been working on documentation :)

**Comment by rsinghal** [comment]
<img width="1385" alt="screen shot 2015-10-27 at 11 51 52 am" src="https://cloud.githubusercontent.com/assets/2371632/10763681/49c0f014-7ca1-11e5-8065-89edb957a78a.png">

**Comment by rsinghal** [comment]
<img width="1388" alt="screen shot 2015-10-27 at 11 55 23 am" src="https://cloud.githubusercontent.com/assets/2371632/10763775/a7fb52f0-7ca1-11e5-83fe-9f07955a1a06.png">

<img width="180" alt="screen shot 2015-10-27 at 12 03 10 pm" src="https://cloud.githubusercontent.com/assets/2371632/10764078/e574ffc2-7ca2-11e5-8558-cfb2d86d6122.png">
