### ISSUE TITLE
Mirador not displaying all loaded objects in Firefox

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#617]
OS X 10.9.5, Firefox ESR 31.8.0

No errors in Console, requests for manifests are not throwing any errors.  Inconsistent number of manifests showing in manifest list page

<img width="1480" alt="screen shot 2015-08-10 at 11 13 48 am" src="https://cloud.githubusercontent.com/assets/2371632/9174926/e56ec7fe-3f50-11e5-9048-d4187ef494d6.png">
<img width="1480" alt="screen shot 2015-08-10 at 11 14 53 am" src="https://cloud.githubusercontent.com/assets/2371632/9174951/0f8f24e8-3f51-11e5-98c2-c424d9c5d07d.png">
<img width="1480" alt="screen shot 2015-08-10 at 11 14 41 am" src="https://cloud.githubusercontent.com/assets/2371632/9174952/0f90c64a-3f51-11e5-83f6-23508bb94745.png">

**Comment by edsu** [comment]
I'm seeing this in Firefox too. If you reload it a few times does it sometimes work, like this example? http://ec2-52-7-99-163.compute-1.amazonaws.com/clippings/00004/ I wonder if it's a timing issue of some kind?

**Comment by edsu** [comment]
This is probably a long shot, but I wonder if latest Firefox is respecting synchronous XMLHttpRequests, like this one in [SaveController](https://github.com/IIIF/mirador/blob/master/js/src/utils/saveController.js#L54). I've noticed Chrome complaining that it is deprecated...

**Comment by rsinghal** [comment]
This does seem related to the latest version of Firefox (39.0.3), released 8/6, since I tried 39.0 and things *seemed* to be working correctly.  This is the only release note: https://www.mozilla.org/en-US/security/advisories/mfsa2015-78/.

**Comment by rsinghal** [comment]
Spoke too soon, this issue is appearing in 39.0 as well.

**Comment by edsu** [comment]
:disappointed: 

What about pre 30.0? I don't know if I'm reading [this](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#Synchronous_request) correctly, but perhaps the synchronous XMLHttpRequest was removed?

**Comment by edsu** [comment]
FWIW, I'

**Comment by rsinghal** [comment]
Looks like we put an event publisher before the listeners for that event.  Chrome and Safari must load everything first before running the JS, while Firefox does not, so there can be an issue with timing.  Need to do some more testing, but should be able to push a fix tomorrow.
