### ISSUE TITLE
Add "Thumbnail View" option to Image/List/Scroll View drop-down

### ISSUE THREAD

**Issue by janettaylor** [IIIF/mirador#700]
During fall semester of 2015, several Harvard librarians performed a usability test on the Harvard Library's instance of Mirador.  All test participants experienced issues with toggling the thumbnail view.  The users could not easily tell which view is currently selected or where to find the thumbnail view.  The librarians recommended removing the separate thumbnail view icon and adding a "Thumbnail View" option to the list that includes Image View, List View, and Scroll View.  The existing grid icon could be used for the Thumbnail View option.  Additionally, the icon should dynamically change based on which view is currently selected.

**Comment by aeschylus** [comment]
Thanks for taking the time to ticket this, and for conducting this testing in the first place. We've certainly heard this feedback before, and have tried a number of things. I've created another ticket (#701) to address the button state issue.

Perhaps it is time to give this configuration a try (and see if anyone misses the thumbnail view button outside of the dropdown).

Thanks again!

**Comment by rsinghal** [comment]
I like the idea of having the drop down menu be more dynamic based on the current view type.
