### ISSUE TITLE
Create configurable behavior of saving the last used view for a given canvas on a given slot

### ISSUE THREAD

**Issue by beaudet** [IIIF/mirador#702]
As ConservationSpace users navigate through images they have added into Mirador via the ConservationSpace ImageWidget, we want to provide them with the ability to save the last viewed state  for all canvases within a manifest.  This means that Mirador would need to save a copy of view information (zoom level, offset, transparency, brightness, etc.) as users are traversing various manifests so that when they return to an image they had previously zoomed to a specific spot, that view is reconstituted when they navigate to it again.  This behavior should probably be configurable so that the default is to NOT save the view of a canvas.   The would not survive a slot reset unless the data is persisted by an external application and reconstituted into the manifest itself or otherwise applied via Mirador APIs.

**Comment by aeschylus** [comment]
Mirador already does this, and persists it. There is currently a nearly-complete PR ( #565 ) out for making this more configurable. This would allow any back-end to be used.

**Comment by rsinghal** [comment]
@aeschylus Yes and no.  Mirador saves the current workspace state, but does not preserve it when a user switches manifests (or even canvases within a manifest).  There will need to be a bit more work that will need to be done to manage the state for each canvas, and make it persist.  And I agree with @beaudet that the default should be that it does not do this.

**Comment by beaudet** [comment]
Presumably this would be affected heavily by the (Manifold / Manifesto?) integration work.

**Comment by aeschylus** [comment]
@beaudet Review for timeline purposes? Closing for now.

**Comment by beaudet** [comment]
Addressed through IIIF manifest layouts and the ability to extract Mirador state from the application programmatically.
