### ISSUE TITLE
Ability to lock out Mirador user interface controls

### ISSUE THREAD

**Issue by beaudet** [IIIF/mirador#707]
The ConservationSpace project has a need to deny certain users the ability to navigate through a manifest.  Instead, a canvas view will be reconstituted but users will only be able to view the resulting canvas as if it is a static image. No ability to pan / zoom, annotate, etc. will be enabled in this mode.

I imagine we would want UI Lock to be a Mirador start-up parameter and that the UI could be unlocked by an API if needed without having to reload Mirador.

**Comment by rsinghal** [comment]
I have to ask the question - why use Mirador to display, essentially, a static jpg (using the Image API)?

**Comment by beaudet** [comment]
This is an edge case in the application but since we're using Mirador to reconstitute views, annotations might be displayed, or brightness / contrast adjusted, etc.  So Mirador is still required to reproduce the view - a IIIF image URL would be insufficient by itself.  I raised one eyebrow as well when I first heard of this requirement although I never followed up on this one because it sounded pretty easy to accommodate, but I'll dig into the user story a little more and supplement the description.

**Comment by beaudet** [comment]
Given recent decisions about supporting different modes of Mirador based on whether a ConservationSpace author is editing vs. viewing, this is no longer a requirement, so I'm going to close the ticket.  Thanks for challenging the assumption.
