### ISSUE TITLE
many additions to set of available annotation markers

### ISSUE THREAD

**Issue by beaudet** [IIIF/mirador#709]
The ConservationSpace project needs support for the following additional annotation markers:
* add pins, lines, circles, free-form text (drawn text) as well as controls for colors, borders, line types, and the ability to edit shapes after creation
* add ability to associate multiple markers with a single annotation as I think is being described in https://github.com/IIIF/mirador/issues/628

Questions:
* should the annotation lists be referenced by manifests and in JSON-LD format, conforming to OA standards?
* does OA (via SVG presumably) support user-entered (but not drawn free hand) text as annotation markers?  In other words, can one define a label (in computer type) in SVG that OA would represent as type on the target itself?  Could one create an annotation marker "rip here is very small" with a more embellished annotation text associated and have the marker appear as type on the screen or are we limited to free-hand drawn text using lines, arcs, etc.?
* It seems like the proper approach is to make the annotation lists available in JSON-LD and OA compliant and to reference those lists from within the manifest.  Can you confirm that?

Related issues: https://github.com/IIIF/mirador/issues/403 https://github.com/IIIF/mirador/issues/626 https://github.com/IIIF/mirador/issues/340

**Comment by aeschylus** [comment]
Most of this has been handled by #840 n'est pas?

**Comment by rsinghal** [comment]
#840 hasn't been merged, and will not be merged directly into release2.1 in the immediate future in order to have the opportunity to fix a number of outstanding issues before it can be a part of release2.1
