### ISSUE TITLE
enhance canvas manipulation controls

### ISSUE THREAD

**Issue by beaudet** [IIIF/mirador#710]
The ConservationSpace project needs the following additional canvas manipulation controls to be built into Mirador:

* brightness and contrast of canvas - see https://github.com/IIIF/mirador/issues/375
* transparency slider for canvas pinned to the foreground as a transparent overlay
* control to lock pan/zoom for canvas pinned to the foreground as a transparent overlay and the currently selected canvas
* finer grained zoom control (mousewheel and buttons too coarse) - see https://github.com/IIIF/mirador/issues/411
* rotation control (TBD whether arbitrary or limited options - if arbitrary, will need fine grained control) - see https://github.com/IIIF/mirador/issues/695
* ruler for conveying physical size of the canvas based on metadata in the manifest - see https://github.com/IIIF/mirador/issues/97 , https://github.com/IIIF/mirador/issues/493 , and https://github.com/IIIF/mirador/issues/305 - it seems that OpenSeadragon has a module that supports this?

Questions:
* how should brightness / contrast / transparencies be persisted?  In manifest?  If in manifest metadata, is there a preferred standard?
* do any IIIF servers support arbitrary rotation or are they locked to 90,180,270 currently?
* what is the proper method for representing the physical dimensions of an object / canvas in a manifest?
* are brightness / contrast to be included in Mirador 2.1?

**Comment by thehabes** [comment]
The brightness, contrast and rotation controls introduced do not persist.  They are a client side HTML filter.  I suspect a similar approach would be successful for implementing the transparency slider.  To see a working implementation go to http://165.134.241.141/brokenBooks/getManifest.html.  The tools are available via a white icon on the right side of the screen, click to toggle them and use them.

Officially, there is no way to make these persist.  A workaround that I have implemented in the past is to store this information as annotations to the canvas, then detect these via their label and apply the values to html filters on canvas load.  However, this is not native behavior to the Mirador UI nor its API requests.  

For information on how to represent the physical dimensions of a canvas, visit this page: http://iiif.io/api/presentation/2.0/#descriptive-properties

As for rotation, read into that here: http://iiif.io/api/image/2.0/#image-request-parameters .  The API requests can be manipulated to have a IIIF compliant server serve images at a given rotation.  The UI rotation tools built only do 90/180 degree rotations, and these do not persist, so manipulating the API to serve your images rotated may be the best solution for you.

I cannot help you much with the rest of your concerns, someone in a better position than I will speak to those.  I hope this is somewhat helpful to you!

**Comment by beaudet** [comment]
Bryan, this is great information and I hope our development team is able to use your implementation.  Thank you.  Despite the fact that metadata standards do not exist for view state, I'm hopeful that using the built-in (and seemingly flexible) metadata specs for the IIIF presentation's canvas might present an avenue for persistence or at least for conveyance of the settings.  Rob referenced https://github.com/IIIF/mirador/pull/565 as a good option for persisting the views of canvases and also pointed out the existence of the Mirador currentConfig property in a comment here https://github.com/IIIF/mirador/issues/703.  Lots to ponder, but we probably won't make a persistence decision until after the Ghent meetings next week.

**Comment by aeschylus** [comment]
@beaudet 

Break out anything that's still relevant? Closing for now.
