### ISSUE TITLE
Need tools for managing/editing annotations (Vatican library Issue #1 of 6)

### ISSUE THREAD

**Issue by seancmartin** [IIIF/mirador#731]
Based on the experience of managing a set of detailed annotations on a pilot of one folio, there is a need for a tool for the creation, editing, and deletion of annotations, especially for changing the coordinates of the border of the annotation, and including support for features reported in VL#2-6 if/when these are addressed. It was time consuming creating detailed annotations for a pilot of one folio, hence such a tool would be required for routine “production” involving the systematic annotations of multiple works.
![hash1image1](https://cloud.githubusercontent.com/assets/10401019/12055140/3f952eb2-af22-11e5-92ef-d166bc3f5476.jpg)
![hash1image2](https://cloud.githubusercontent.com/assets/10401019/12055143/43a57be2-af22-11e5-87f5-f437ee5bed8c.jpg)

**Comment by rsinghal** [comment]
related to #709
