### ISSUE TITLE
Need support for non-rectangular/irregular regions (Vatican library Issue #2 of 6)

### ISSUE THREAD

**Issue by seancmartin** [IIIF/mirador#732]
An example is shown with the irregular region shown in red in the first figure where the region had to be implemented as three rectangles. The example shows straight lines, but curved lines, as part of the bounding box, would be useful in some circumstances.
![hash2image1](https://cloud.githubusercontent.com/assets/10401019/12055199/d757034c-af22-11e5-81b3-2e88bb4476d2.jpg)
Support for arcs or circles, such as SVG Circle, is desirable (see http://www.w3schools.com/svg/svg_circle.asp ). The following example (which is not a Vatican image) shows a series of circular photographs where each could be identified as a circle with an annotation comprising the individual’s name. (See  http://vps.appliediiif.org.uk:3128/iiifImageService/Clerge_du_Diocese_du_Montreal_(HS85-10-10091)_original/1250,2734,1024,1024/!256,256/0/native )
![hash2image2](https://cloud.githubusercontent.com/assets/10401019/12055207/ecfaaaf0-af22-11e5-9073-8fa675f2b26c.jpg)

**Comment by rsinghal** [comment]
related to #709
