### ISSUE TITLE
Need support for an annotation that applies to multiple regions (Vatican library Issue #5 of 6)

### ISSUE THREAD

**Issue by seancmartin** [IIIF/mirador#735]
One annotation relates to multiple separate or disjoint regions. The description for such an annotation may apply to multiple regions, hence this would be a one to many mapping.
In the example shown in the figure the same description applies to the four “yellow” regions, where one is an irregular shaped region.

![hash5image1](https://cloud.githubusercontent.com/assets/10401019/12056149/6cf3d8a0-af2b-11e5-8e01-96dd50dc555d.jpg)

**Comment by rsinghal** [comment]
related to #709
