### ISSUE TITLE
Being able to edit a shape should be triggered when clicking on its border

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#764]
Rather than inside the shape, otherwise it's impossible to select a shape that is completely inside of another.

Also, the current behavior is when you click inside a shape the first time and you move the mouse, it immediately starts moving the shape. The initial click on the border should select the shape, but the user should have to click and move the mouse to move the shape.

#748

**Comment by rsinghal** [comment]
@stanislavkostadinov Triggering a shape to be edited should occur when you click on a border.  Otherwise, it's 1) impossible to select a shape inside of another shape and 2) impossible to draw a shape inside of an existing shape.  

Please fork and work off the [refactor](https://github.com/IIIF/mirador/tree/refactor) branch as I have merged all of your annotation work into there along with refactoring that I did.  I had to move some code around, but it should generally look as you expect it to.

**Comment by stanislavkostadinov** [comment]
I'm working on that problem and I'll create PR asap.

**Comment by aeschylus** [comment]
What are the statuses of the annotation issues. Do any of the ones tagged "annotation" need to be updated?

**Comment by rsinghal** [comment]
This hasn't been merged
