### ISSUE TITLE
Update annotation icons

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#765]
(drawing tools)
rectangle - https://design.google.com/icons/#ic_check_box_outline_blank
circle - https://design.google.com/icons/#ic_radio_button_unchecked
polygon - https://design.google.com/icons/#ic_timeline
pin - https://design.google.com/icons/#ic_room
freehand - https://design.google.com/icons/#ic_gesture
(color pickers)
border color - https://design.google.com/icons/#ic_border_color
color fill - https://design.google.com/icons/#ic_format_color_fill

And use the same convention (gray if it is not selected, white if it is) to make it clear which shape/tool is currently selected 

#748

**Comment by stanislavkostadinov** [comment]
Done

**Comment by yuricus** [comment]
At latest pull request Material Icons were introduced, but unlike other Mirador dependencies, they are not bundled with Mirador itself (like font-awesome) but css and font is loaded through Google Web Fonts, it adds additional external dependency and does not align with Mirador packaging. Should we consider to bundle it within Mirador?

**Comment by yuricus** [comment]
Actually, I've done it locally but how to merge changes? where to provide pull requests to?

**Comment by stanislavkostadinov** [comment]
If @rsinghal prefers self hosting of font to Google Web Fonts you can merge your code to this branch (https://github.com/SirmaITT/mirador/tree/feature_annotation_tool).

**Comment by rsinghal** [comment]
Yes, I think we should add the Google font to the Mirador build so we don't have external dependencies.  Have you pushed your latest updates to PR748?

**Comment by stanislavkostadinov** [comment]
Yes, I have
