### ISSUE TITLE
Can't use mouse to pan when annotations are visible

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#774]
@stanislavkostadinov 

When I turn on annotations (but am not trying to edit/create new annotation shapes), I can't pan using the mouse with click and drag. Zooming with the mouse does work.

**Comment by rsinghal** [comment]
Related - double click for zooming also doesn't work.

**Comment by stanislavkostadinov** [comment]
Last commit from  #773 fixes that problem
