### ISSUE TITLE
Move window close button outside of dropdown to top left of window (same location as the slot close button)

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#783]
<img width="1007" alt="screen shot 2016-03-07 at 10 28 02" src="https://cloud.githubusercontent.com/assets/145874/13578882/517d31a8-e44f-11e5-91f2-ed301cfb506d.png">

**Comment by beaudet** [comment]
Couple of observations:

1. in default OSX, the close window "x" appears within a red circle in the upper left and (only when?) hovering? I don't have a mac handy right now, so am relying on google screenshots.   In Windows, the "x" is persistent and in the upper right corner.
2. in the screenshot of this proposal, the icons for "full screen" appear like a fancy X and might be confused with a close button for those accustomed to looking for it in the upper right.
