### ISSUE TITLE
Collapse all canvas controls (except basic navigation) into a single hierarchical menu.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#789]
<img width="936" alt="screen shot 2016-03-07 at 10 35 43" src="https://cloud.githubusercontent.com/assets/145874/13579137/9b77eefa-e450-11e5-9afa-dcff62e1562a.png">
<img width="924" alt="screen shot 2016-03-07 at 10 35 54" src="https://cloud.githubusercontent.com/assets/145874/13579139/9d7ab8b8-e450-11e5-856e-66e3d9b0cadd.png">

**Comment by aeschylus** [comment]
We should probably discuss what this means for configuration, since many people will want very specific sets of these tools in very specific orders to be displayed on the canvas.

**Comment by stanislavkostadinov** [comment]
The order of the tools depends on the order of the `availableAnnotationDrawingTools`.
