### ISSUE TITLE
Missing hover states on links in annotation body

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#810]
_(tested on release2.1 branch)_

![screehshot](https://cloud.githubusercontent.com/assets/402117/14135675/20bbd552-f65f-11e5-917c-ac85a77f5187.jpg)

**Comment by rsinghal** [comment]
@regisrob Can you look at `810-missing-hover-state` and let me know if that is what you were looking for?  It's the same hover effect that we use in the metadata panel

**Comment by regisrob** [comment]
Thanks Rashmi, I'm sorry the ticket was unclear and it did not mean what I was expecting  :grin:
Indeed the hover state on links in annotation body was missing, but what I want to point out is the need to visually distinguish the text from links: i.e. links must have a default state that makes them visible in annotation body and metadata panel. Maybe the bottom border should be default (and no border the hover effect, with or without a little color change, like grey?). What would you prefer?

**Comment by rsinghal** [comment]
I agree - that makes sense.  Can you take a look at the latest in the branch now?  We can change the hover color, but it never made sense to me that links in the metadata view were not decorated in some way.

**Comment by regisrob** [comment]
Thx. I think it's ok like this :wink:
