### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#821]
@aeschylus I did a fresh install of nodejs/npm/grunt and get a lot of warnings when running `npm install`, such as:

```
npm WARN package.json Mirador@2.0.0 No license field.
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.4.2","npm":"2.15.0"})
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-git-describe will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.5 included from grunt-coveralls will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
...
```
which eventually leads to the following error:
```
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-karma@0.10.1 wants grunt@0.4.x
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-connect@1.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-githooks@0.3.1 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-git-describe@2.3.2 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-coveralls@1.0.0 wants grunt@~0.4.5
npm ERR! peerinvalid Peer grunt-karma-coveralls@2.5.4 wants grunt@*
npm ERR! peerinvalid Peer grunt-template-jasmine-istanbul@0.3.4 wants grunt@>=0.4.0
```

**Comment by rsinghal** [comment]
Specifically, `grunt` must be >=0.4.5 and < 0.5  and the latest version is 1.0.1

**Comment by aeschylus** [comment]
Looking into this now (during the call).

**Comment by aeschylus** [comment]
https://github.com/gruntjs/grunt/issues/1488

**Comment by dvhassel** [comment]
on a fresh node.js installation on Windows7, I'm unable to build Mirador2.x: 

120590 error Failed at the Mirador@2.0.0 postinstall script './node_modules/grunt-cli/bin/grunt githooks'.
120590 error This is most likely a problem with the Mirador package,
120590 error not with npm itself.
120590 error Tell the author that this fails on your system:
120590 error     ./node_modules/grunt-cli/bin/grunt githooks

**Comment by thehabes** [comment]
Same for me today.  Here is the console output:

C:\Users\bhaberbe\Documents\mirador [release2.1]> npm install
npm WARN package.json Mirador@2.0.0 No license field.

> Mirador@2.0.0 postinstall C:\Users\bhaberbe\Documents\mirador
> ./node_modules/grunt-cli/bin/grunt githooks

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! Mirador@2.0.0 postinstall: `./node_modules/grunt-cli/bin/grunt githooks
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Mirador@2.0.0 postinstall script './node_modules/grunt-cl
i/bin/grunt githooks'.
npm ERR! This is most likely a problem with the Mirador package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/grunt-cli/bin/grunt githooks
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Mirador
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls Mirador
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bhaberbe\Documents\mirador\npm-debug.log


Attatched is the debug.  
[npm-debug.txt](https://github.com/IIIF/mirador/files/298216/npm-debug.txt)

**Comment by wkentdag** [comment]
I'm also unable to install mirador via npm, as it fails on the `postinstall` command `grunt githooks`:

```
⚡ iiif-viewer@master ~ node -v
v6.2.0
⚡ iiif-viewer@master ~ npm -v
3.10.6
⚡ iiif-viewer@master ~ npm i -S IIIF/mirador

> Mirador@2.0.0 postinstall /Users/wkentdaggett/local-dev/iiif-viewer/node_modules/Mirador
> grunt githooks

grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "IIIF/mirador"
npm ERR! node v6.2.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! Mirador@2.0.0 postinstall: `grunt githooks`
npm ERR! Exit status 99
npm ERR! 
npm ERR! Failed at the Mirador@2.0.0 postinstall script 'grunt githooks'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Mirador package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt githooks
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Mirador
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Mirador
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wkentdaggett/local-dev/iiif-viewer/npm-debug.log
⚡ iiif-viewer@master ~ 
```

I attempted to workaround the issue by forking the repo and removing the postinstall command ([here](https://github.com/wkentdag/mirador/commit/b8569c15ef974a93a4690cb1824b3e3c46f0f9b5)), but experienced the same error.
