### ISSUE TITLE
Should we show/hide canvas controls on hover?

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#839]
I thought back on that while looking at the Mirador demo William gave us on yesterday IIIF call. In his Mirador instance, the rotation buttons were placed in the window top bar (that is supposed to represent the "manifest" level if I understood well the UI principles). The reason given for that was to avoid covering up any part of the manuscript in the ImageView.

Indeed it could become a problem as the number of controls at the canvas level is going to increase (default navigation controls, annotations tools, image manipulation tools, image choice, detail images, with sliders, text labels and so on...). I know there will be a "gear" or "toolbox" icon to toggle all of them at once but it might be a pain for a user to click on it every time he wants to have a clearer view of the image.

Could we simply show/hide these controls when hovering the canvas/image viewport?
This is what UV does (http://universalviewer.io/examples/). It may be a good solution, but on the other hand it could also be seen as a "distraction" (not sure if it is the appropriate word...)

What do you think?

**Comment by rsinghal** [comment]
Yes, this is similar to #324.  I like the idea of having the controls auto hide and hopefully wouldn't be too distracting or confusing.

**Comment by regisrob** [comment]
:ok_hand:

**Comment by aeschylus** [comment]
This has been implemented, but requires some additional tweaking to reduce distraction and improve the performance (the mousemove event seems to block the thread). Closing for now though. I will create another ticket for the related quibles.
