### ISSUE TITLE
Change mouse cursor over annotation border

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#841]
In edit mode, I think it would be helpful for the mouse cursor to change to the pointer when the mouse is over a border - to indicate that the user can click and select it
@stanislavkostadinov

**Comment by aeschylus** [comment]
@rsinghal @beaudet Is this solved in 840 or are we waiting for the redux? I'm pruning issues.

**Comment by rsinghal** [comment]
Hasn't been merged yet

**Comment by beaudet** [comment]
I don't believe this was part of #840 commit and the revised annotation design described in #881 doesn't specify a change in mouse cursor when hovering over shapes of an annotation being edited, although the behavior is somewhat different so I don't know if it's necessary anymore.  After clicking on the "edit" link of the annotation pop-up, the shapes associated with an annotation are to be highlighted so it will be apparent to the end-user which shapes can be clicked on - it's easy enough to modify the design of #881 though so if you think this is still needed, it could just be added to that issue.

**Comment by aeschylus** [comment]
I was trying to help Stu in creating some videos for the viewers presentation tomorrow and we noticed a lot of strange annotation behaviour with the current release branch. I know you and @rsinghal have reviewed this pretty thoroughly. Would all of that be accounted for in the 3-4 issues you guys created about 840? If not, can you link to some other documentation you guys created?

**Comment by stanislavkostadinov** [comment]
This was part of #840 commit.
