### ISSUE TITLE
Configuration item "annotationCreation" needs refinement.

### ISSUE THREAD

**Issue by gigamorph** [IIIF/mirador#851]
Currently if "annotationCreation" is set to false, the annotation creation/edit mode is disabled, but you can still update or delete exiting annotations by hovering over the them. It seems more natural that update and delete shouldn't be allowed either if creation is disabled.

**Comment by rsinghal** [comment]
The annotation store should determine whether or not an annotation can be deleted/updated through permissions. The point of `annotationCreation` is to allow a user to prepopulate annotations that are displayable to other users, but the annotation store does not allow those other users to update/delete the annotations, so it makes them read-only for the end users.  This type of control and display of annotations is essential in courses.

**Comment by gigamorph** [comment]
I'm confused. If annotationCreation is false, the read-only end users will still see the "edit" and "delete" buttons, which is confusing because it'll let them edit and delete the annotation on screen but it won't be saved in the annotation store. How can I hide those edit and delete buttons then?

**Comment by rsinghal** [comment]
That depends on your annotation store and the endpoint module that you wrote for it.  Each endpoint module has a `userAuthorize` function that handles the permissions for that particular store.  By default, it will return true.  `catchEndpoint` is an example of doing more in depth permission checking, which then affects the display of the edit/delete buttons.

**Comment by gigamorph** [comment]
Thank you!
