### ISSUE TITLE
PR 840 Redux: Shape and Layer Transformation Control Enhancements

### ISSUE THREAD

**Issue by beaudet** [IIIF/mirador#880]
@stanislavkostadinov - There are some UX enhancements the community has requested to PR 840 and related annotation features.  @rsinghal  has created a new annotations branch based off of the current Mirador 2.1 branch and is committed to keeping it up-to-date while these enhancements are worked on.  Please resubmit PR 840 to the new annotation branch.  @rsinghal  will merge immediately with that branch and then you can proceed with these enhancements.  @rsinghal has committed to keep the annotations branch in sync with Mirador 2.1 as progress on Mirador 2.1 release is committed.

There are two types of transformable objects involved in ConservationSpace contributed Miraodr features: annotations and (soon to be) image layers.  This design applies to both types, although layer transformation features will be performed as part of the layers tab ticket which will be submitted in a few days after the community has reviewed the designs.

Refer to the design document here: 

https://drive.google.com/file/d/0B8dnsz8s0G6eWVBmdmpsakl2bEk/view?usp=sharing

Annotation Shape Transformation Control Enhancements Requests:
1.	Rotation controls should only permit rotation
2.	Dilation controls should only permit dilation
3.	There should only be a single handle for the pin / marker annotation type and it should be rendered at the origin of the shape, e.g. the point where a human naturally understands would be the specific point associated with an annotation
4.	Translation of individual points is the only transformation currently supported for freehand shapes – it is not necessary to rotate or dilate freehand shapes such as the line, arbitrary polygons, and splines.  Uniform translation of all points of a shape can be accomplished by clicking and dragging on (or in a closed polygon, inside) the shape, but not on a transformation handle.
5.	Dilation of standard shapes such as ellipses and rectangles should occur relative to a corner of the bounding box of the object rather than the geometric center, i.e. the handles diametrically opposed to the selected handle should be anchored during the dilation.
6.	Rotation of objects should occur around the geometric center and there should be a single rotation control per object, clearly identified with a standard rotation icon, e.g.  , and offset slightly from the top of the shape.
7.	Optionally provide additional handles for standard shapes that permits dilation in a single axis, e.g. squeeze or widen along x-axis or y-axis only (not to be applied to image layer transformations).

Please submit the functionality in the following order and in separate PRs to make review of the code easier:

PR #1: {Rotation function: present a single rotation icon for shapes, offset slightly from the top of the shape outline. Only rotation around the geometric center of the object should be performed – no dilation of the shape should occur when rotating.} - see design document
PR #2: {Dilation function: only standard geometric shapes can be dilated uniformly; dilation should occur by anchoring the corner diametrically opposed to the handle being dragged - see below for individual point translation of arbitrary polygons, splines, and markers} - reference design document
PR #3: {Translation of shapes: pin / markers should have a single point corresponding to the “point” of the shape which is the anchor of the marker.  Non-standard shapes like arbitrary polygons and splines can have individual points moved one at a time which changes the shape; any shape can be moved in its entirety without altering the shape's dimensions by dragging on the interior of a closed shape or on the border of an open shape; } - reference design document

**Comment by radpet** [comment]
@rsinghal Is there something else to be implemented from this issue?
