### ISSUE TITLE
Two full screen toggles, and one disappears

### ISSUE THREAD

**Issue by snydman** [IIIF/mirador#896]
Upon opening a single object in mirador 2.1.x I see two full screen controls:  one for the object window, and one for the app. 

![image](https://cloud.githubusercontent.com/assets/3279382/15058540/a99e5924-12d1-11e6-8bba-c48d6efdc113.png)

If I click the object full screen control, then escape from it, both come back.  

If I click on the app-level full screen control, then escape out, the object-level full screen control disappears.

![image](https://cloud.githubusercontent.com/assets/3279382/15058573/e3172276-12d1-11e6-9e44-c55e53732e4c.png)

What is the intended behavior.  Should there be two controls?  Clearly one shouldn't disappear.

**Comment by rsinghal** [comment]
It works correctly when clicking on the icons, but doesn't properly capture the esc action.
