### ISSUE TITLE
TOC materials cause strange flashing of top bar.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#915]

**Comment by rsinghal** [comment]
Copied this from gitter:
`jQuery(toOpen)` is an array of three items: `[false, li.has-child.selected.open, li.leaf-item.selected.open]`. the first one is finding any ul element in mirador, which those main menu items are. so specifically, the code to create [`toOpen`](https://github.com/IIIF/mirador/blob/release2.1/js/src/widgets/toc.js#L197) is doing something bad
