### ISSUE TITLE
Annotations: cannot reference property "add" of null.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#917]
Create an annotation, delete it, then try to create a polygon. Close the polygon. Click outside of the area, and the polygon disappears, and then all subsequent annotation attempts fail, giving the error.

**Comment by rsinghal** [comment]
The designs that @beaudet and I create should avoid this situation since it should become impossible to click outside of the area without saving or canceling the creation of an annotation.  But should double check again after @stanislavkostadinov implements the changes.

**Comment by dicksonlaw583** [comment]
Can't seem to reproduce on 2.1 anymore. Probably fixed.
