### ISSUE TITLE
In-manifest annotations not being aligned properly with canvas.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#918]
<img width="471" alt="screen shot 2016-05-09 at 10 02 43" src="https://cloud.githubusercontent.com/assets/145874/15128383/8c7149ac-1609-11e6-981c-28cd76183130.png">

**Comment by aeschylus** [comment]
Try the Oto Ege and open annotations.

**Comment by rsinghal** [comment]
The manifest is http://dms-data.stanford.edu/data/manifests/Stanford/ege1/manifest.json

**Comment by stanislavkostadinov** [comment]
I'm not a 100% sure, but I think there is a bug-fix assosiated with that problem over here: #840
