### ISSUE TITLE
Update index.html with more examples

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#924]
- [ ] Provide manifests from more institutions
- [x] Replace Biblissima manifests with Gallica links (#919)
- [x] Replace oculus-dev Harvard links with official Library and Museum links
- [x] Prune the number of Harvard and Stanford manifests to better reflect all of the institutions that use Mirador

updates are being added to `manifests-index`

**Comment by aeschylus** [comment]
What's a good number of manifests total, 60? Could we try to get 5 really good items from 12 institutions?

I vote to keep the scrolls, the Van Gogh, and the Richardson (we don't really have a choice), and the Apostle.

**Comment by rsinghal** [comment]
That number seems reasonable.  Anywhere between 2-5 manifests per institution would work well.  More representation of institutions (especially those that are using Mirador) would be really great

**Comment by rsinghal** [comment]
We can keep the extra Harvard and Stanford ones commented out, but I want that manifest page to look really nice for demos

**Comment by mikeapp** [comment]
Here are a couple of favorites from Yale:
Sir Joshua Reynolds RA, 1723–1792, British, Mrs. Abington as Miss Prue in "Love for Love" by William Congreve, 1771
http://manifests.britishart.yale.edu/manifest/5005

Studio of Francis Harwood, 1726/7–1783, British, active in Italy, Bust of a Man, ca. 1758
http://manifests.britishart.yale.edu/manifest/54430
[The Getty has another copy of this...]

**Comment by regisrob** [comment]
In addition to those from Gallica proposed in [another comment](https://github.com/IIIF/mirador/pull/919#issuecomment-218585265), I suggest adding a few ones from the Vatican Library, potentially... (but no manifest logo provided :disappointed:). Example: http://digi.vatlib.it/iiif/MSS_Vat.lat.3225/manifest.json

**Comment by blalbrit** [comment]
@regisrob - are you able to get the images to load off of that (and other) Vat manifests? I get only thumbs.

**Comment by regisrob** [comment]
@blalbrit yes it works fine for me in the latest Mirador build as well as in an older version of Mirador... This is strange.

**Comment by blalbrit** [comment]
@regisrob all good now.

**Comment by rsinghal** [comment]
@mikeapp I tried adding http://manifests.britishart.yale.edu/manifest/5005 to the `index.html`, but I'm getting the `No 'Access-Control-Allow-Origin' header is present on the requested resource.` error.  But, when I tried adding http://manifests.britishart.yale.edu/manifest/1474, it worked with no errors.

**Comment by rsinghal** [comment]
@glenrobson Do you have a few items that you would like included?

**Comment by glenrobson** [comment]
Thanks will ask around here for 2-5 items. I take it we're not restricted to manuscripts? 

Cheers

Glen

**Comment by rsinghal** [comment]
Nope, feel free to choose anything you like!

**Comment by beaudet** [comment]
I will work on a manifest from the NGA for this.

**Comment by jbhoward-dublin** [comment]
I'll add a few from UC Dublin ... large format architectural elevations, a map with linked geo service, & a goecoded historical photo - John

**Comment by schwemmer** [comment]
Cod. Bodmer 600a – The Life of Buddha, first volume (Shaka no Honji, jō):
http://www.e-codices.unifr.ch/metadata/iiif/fmb-cb-0600a/manifest.json

**Comment by mikeapp** [comment]
I fixed the issue with http://manifests.britishart.yale.edu/manifest/5005

**Comment by regisrob** [comment]
Another suggestion: one famous papyrus from the Vatican, Pap.Bodmer.VIII http://digi.vatlib.it/iiif/MSS_Pap.Bodmer.VIII/manifest.json

**Comment by regisrob** [comment]
Two wonderful medieval maps from the BnF:

**1/ "Atlas Miller", masterpiece of portuguese cartography (1519).** 
Six illuminated maps depicting the known world of the Europeans before Magellan's expedition (1519-1522)

_Atlas nautique du Monde, dit atlas Miller] ; 2-5_
[Feuille 3 r° : Océan Indien Nord avec l'Arabie et l'Inde] ; [Feuille 3 v° : Océan Indien Sud avec l'insulinde à gauche et Madagascar à droite
http://gallica.bnf.fr/iiif/ark:/12148/btv1b55002605w/manifest.json

More info:
http://gallica.bnf.fr/ark:/12148/btv1b55002605w/f1.item.r=
http://gallica.bnf.fr/services/engine/search/sru?operation=searchRetrieve&version=1.2&collapsing=disabled&query=dc.relation%20all%20%22cb40887479k%22
http://expositions.bnf.fr/marine/albums/miller/index.htm

**2/ Catalan atlas from Majorca (ca 1375) :**

_Abraham Cresques , Atlas de cartes marines , dit [Atlas catalan]_
http://gallica.bnf.fr/iiif/ark:/12148/btv1b55002481n/manifest.json

More info:
http://gallica.bnf.fr/ark:/12148/btv1b55002481n/f7.planchecontact
http://expositions.bnf.fr/marine/albums/catalan/index.htm

**Comment by regisrob** [comment]
One scroll:
Rouleau de parchemin (1301-1400) 
(genealogy of the Christ ; width: 8.75 meters)
http://gallica.bnf.fr/iiif/ark:/12148/btv1b525067595/manifest.json

**Comment by emmastanford** [comment]
Some from the Bodleian:
http://iiif.bodleian.ox.ac.uk/iiif/manifest/51a65464-6408-4a78-9fd1-93e1fa995b9c.json (scroll)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/586a1b64-64b5-429a-bb23-865b99999643.json (early printed book)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/d5e3a9fc-abaa-4649-ae48-be207ce8da15.json (manuscript)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/f19aeaf9-5aba-4cee-be32-584663ff1ef1.json (atlas)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/a8816b77-ca80-4e52-9e36-ec8e9075cb8b.json (manuscript with micrography)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/3b31c0a9-3dab-4801-b3dc-f2a3e3786d34.json (manuscript musical score)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/e32a277e-91e2-4a6d-8ba6-cc4bad230410.json (paintings)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/bea56620-793f-4dee-875d-ff051563292a.json (early printed book)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/390fd0e8-9eae-475d-9564-ed916ab9035c.json (printed book)
http://iiif.bodleian.ox.ac.uk/iiif/manifest/68af37aa-9710-4d98-8922-7cc9b96dfde7.json (poster)

**Comment by peetucket** [comment]
Some images from The Revs Institute Collection:
http://dms-data.stanford.edu/data/manifests/Revs/demo/manifest.json

**Comment by beaudet** [comment]
Some highlights from the NGA:

http://media.nga.gov/public/manifests/nga_highlights.json
