### ISSUE TITLE
METS support

### ISSUE THREAD

**Issue by nemobis** [IIIF/mirador#925]
I see from https://wiki.de.dariah.eu/display/TextGrid/IIIF that some Mirador users also rely on [METS](https://www.loc.gov/standards/mets/mets-home.html) but I don't see any mention of METS here.

Does Mirador have any support of METS, in particular of the structMap (which should be used to generate a TOC and let the user navigate the item)? If not, is any such support planned or possible?

**Comment by rsinghal** [comment]
Mirador displays IIIF manifests.  You will have to convert your METS object to IIIF in order to view it in Mirador.
