### ISSUE TITLE
FF: Mirador in second tab is empty after loading

### ISSUE THREAD

**Issue by radpet** [IIIF/mirador#929]
[mirado2.zip](https://github.com/IIIF/mirador/files/295017/mirado2.zip)

Loading mirador in iframe inside `display:none` parent causes the image to be loaded but not shown.

Steps to reproduce
Open test.html
Wait until the image is loaded.
Go to tab 2 
See that there is no image shown, although it loads the image and if you go to the element which displays the image and set its style to `display:block` it will show it.

It happens under Firefox only. Maybe it is because mirador does not handle the event that sets its canvas to be visible.

**Comment by beaudet** [comment]
This is causing an issue with embedding Mirador in ConservationSpace.

**Comment by rsinghal** [comment]
I can recreate this, but don't know why it's happening.  I look forward hearing about any more information you find.

**Comment by radpet** [comment]
It seems that firefox does not like this line
https://github.com/IIIF/mirador/blob/release2.1/js/src/widgets/imageView.js#L343
Adding display:block via class that I add in the show function fixes it.
I'll be working on this and send pr as soon as I find better way to fix it. By the way it might be jquery show() issue on firefox but I am not sure yet. Any other ideas?
