### ISSUE TITLE
TOC left align

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#933]
There are a few things going on here, and I'm not sure which is the culprit:

I have two manifests with ranges that only have leaf nodes. https://iiif.riksarkivet.se/arkis!C0000263/manifest is a 2.0 range and MS Typ 441 from Harvard is a 1.0 range.  The 1.0 range has leaf nodes as `h2` elements, and they are properly left aligned.  The 2.0 range has leaf nodes that are `h1` elements, and they are center aligned.  I know that the 2.0 range work is not complete, so this could be the problem, or toc.js is incorrectly setting the level for 2.0 ranges.  

In any case, we should never have a case where the labels in the TOC are center aligned.

![screen shot 2016-05-18 at 12 13 39 pm](https://cloud.githubusercontent.com/assets/2371632/15366367/fd6011fe-1cf1-11e6-889d-69a88f95e865.png)

**Comment by aeschylus** [comment]
Are we able to reproduce this with some object?
