### ISSUE TITLE
[2.0] Ranges

### ISSUE THREAD

**Issue by azaroth42** [IIIF/mirador#94]
Support for 2.0 Range definition, which makes it much easier to construct nested ToCs etc, as opposed to the 1.0 definition which was ... underspecified to put it mildly.
In particular, see:
* http://iiif.io/api/presentation/2.0/#ranges
* http://iiif.io/api/presentation/2.0/#technical-properties for the definitions of the range related viewing_hint values

**Comment by rsinghal** [comment]
duplicate of #527
