### ISSUE TITLE
Address confusion around bookmarking feature.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#949]

**Comment by dicksonlaw583** [comment]
**Current state**
- No documentation on the bookmarking API in the Wiki.
- No API call for turning off bookmarking for use cases that don't need it.
- Inadequate support for embedding multiple viewers on one page.
- Dependency on jsonblob.com causes needless network traffic; recent uptick in 500 responses makes bookmarking unreliable.
- Synchronous loading of bookmark states is causing deprecation warnings on Firefox and Chrome.

**Proposed plan of action:**
- Urgent: Remove dependency on jsonblob.com.
  - Short-term: Write tests for and merge #942.
  - Long-term: Come up with backend-free ways to store and share the view state, such as:
    - Short URL parameters or hash anchors, as is standard on other IIIF viewers with bookmarking. (Better for single embedded viewers; iframes required for multiple viewers)
    - Copy-and-paste field for retrieving the current view state, as well as loading a stored view state 
- Document the view state blob format for a bookmark.
- Document the bookmarking API and add an entry to the Wiki entry for Configuration APIs.
from somewhere else. (Workable for both single and multiple embedded viewers)
- Replace the synchronous `readSync` method for the view state blob endpoint with an asynchronous `read` method that returns a promise.
- Ability to configure the method for storing bookmarks, including a null implementation that disables bookmarking altogether.

**Nice-to-haves**
- Make the viewer call the view state blob endpoint's `save` method less often. The current implementation calls this method over a dozen times for a one-second zoom and lags visibly.

**Comment by dicksonlaw583** [comment]
Wiki updated: [Configuring Persistent Bookmarking in Mirador](https://github.com/IIIF/mirador/wiki/Configuring-Persistent-Bookmarking-in-Mirador)

**Comment by aeschylus** [comment]
Close this if the default is changed.
