### ISSUE TITLE
viewer not fully initialized when manifest has no attribuut "description"

### ISSUE THREAD

**Issue by nicolasfranck** [IIIF/mirador#960]
When the manifest does not have the attribute "description",
the viewer does not fully initialize:

  * openseadragon loads
  * thumbnailsView not created
  * info panel on the right not created
  * index tab on the left is open
  ..

it fails somewhere with the error:

  mirador.js:10853 Uncaught TypeError: Cannot read property '@value' of undefined

when setting description to an empty array, this is fixed.

**Comment by rsinghal** [comment]
@nicolasfranck Do you have a manifest at a public URL we can use for testing?

**Comment by nicolasfranck** [comment]
http://shared.ugent.be/local/manifest.json

**Comment by rsinghal** [comment]
I can't recreate this bug using https://github.com/IIIF/mirador/commit/284ffd58e462e567f44250acace6d30ecfffc1fc.  I also checked some other manifests that don't have a `description` and they don't fail.  If you have a public site where this is failing (with the latest release2.1 build) that would be very useful.

**Comment by nicolasfranck** [comment]
I see, in release2.1 it works, but not in the master branch:

Compare:

http://shared.ugent.be/local/mirador_master

with:

http://shared.ugent.be/local/mirador_2.1

I did indeed put this issue on the wrong issue list ;-)
But I'm happy it will be resolved ;-)

Thanks!
