### ISSUE TITLE
Missing arrows/context controls when new image is selected

### ISSUE THREAD

**Issue by radpet** [IIIF/mirador#969]
Use case:
When I am in annotation creation mode and I choose new image, the whole context menu and control arrows/buttons disappear.

All controls are still there but hidden class is added to them.
I will fix it if anyone else have not started working on it.

**Comment by rsinghal** [comment]
Yes, this is a bug with the autohide feature for the canvas controls.  I will fix it.

**Comment by radpet** [comment]
This fixes it, but it causes issue when you save the current anno state (for example you are in annotation explore mode) and then load mirador with this state. It opens the other tools (hopefully they are not active , so it is only css hide/show issue). Furthermore I think it is not from the change you added but mirador seems a little bit laggy to me when I zoom in/out or use the small arrows.
