### ISSUE TITLE
Open mirador in full-screen mode

### ISSUE THREAD

**Issue by radpet** [IIIF/mirador#977]
When I try to activate full screen with opened image the following error is thrown

mirador.js:25756 Uncaught TypeError: _this.fullScreen is not a function

I'll open pull request if noone is working on it now

The fix I have done is to rename the function because it seems something sets the same variable to bool :)

**Comment by radpet** [comment]
@rsinghal do you want to fix it by renaming the function to toggleFullscreen for example?

**Comment by rsinghal** [comment]
Yeah, I'll take a look at it

**Comment by radpet** [comment]
@rsinghal Should I send pr to release 2.1 with the fix?

**Comment by rsinghal** [comment]
yes

**Comment by radpet** [comment]
https://github.com/IIIF/mirador/pull/981
