### ISSUE TITLE
Pin annotation click and drag

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#982]
@radpet 

After I have clicked on an existing pin annotation and released my mouse, I can't re-select it.  Clicking on the pin again causes a new pin to be drawn.  I can cancel that new pin, and then I can select the pin again.  In effect, unless the user clicks and immediately drags the pin to move it, it is impossible to move it after it is created.  However, circles and rectangles behave differently since it is possible to release the mouse and then re-select the shape in order to move it or resize it.

**Comment by beaudet** [comment]
Interesting UI quirk - what do you suggest as a solution?

**Comment by rsinghal** [comment]
Ideally it would behave the same was as the other shapes - namely until you hit save, the user is actively able to edit that shape.  The problem could just be about making the mouse click more sensitive and recognizing that the user is reselecting that pin, but I'm not sure.

**Comment by radpet** [comment]
@rsinghal Currently the pin has 5 point handlers that I cannot selectively disable. That is why I disabled all of them and made its stroke in another color when selected. I can check out why you are not able to drag it once you selected it. Actually I think that this bug will not be present after I implement the pointer tool because you will be able to draw shapes only after selecting the shape tool.

**Comment by rsinghal** [comment]
I can drag it if I don't release the mouse (upon first clicking it), but if I release the mouse, then I can't click on it again until I've clicked on the canvas, canceled the new pin that has been created, and then click on the old pin again (and of course, don't release the mouse).  I will try to make a gif of this if it isn't clear.

**Comment by radpet** [comment]
@rsinghal Yup I got it no need for gifs for now. I will spend some time on this issue, but I have no solution to display only one point handler and preserve the current shape of the pin

**Comment by rsinghal** [comment]
I will look into it as well

**Comment by radpet** [comment]
@rsinghal I checked it out and the code is implemented like that. I suggest changing it so it can handle multiple selections on pins, what do you think?

**Comment by radpet** [comment]
@rsinghal I fixed this in https://github.com/SirmaITT/mirador/tree/feature/delete-shape-action
