### ISSUE TITLE
Limit annotation drawing to within the canvas

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#983]
@radpet 

It should not be possible to draw a shape outside of the OSD canvas since the annotations exist within the context of the annotation.

In `master`, I implemented it by constantly checking the mouse position within the canvas and never letting any of the points stray outside those dimensions (see: https://github.com/IIIF/mirador/blob/master/js/src/annotations/osd-region-rect-tool.js#L107).  Something similar needs to be implemented for all of the new shapes.

**Comment by radpet** [comment]
@rsinghal You mean that I should not be able to draw out of the image bounds? So you say no more drawing in the black borders :(

**Comment by rsinghal** [comment]
Exactly, per the OA spec, https://www.w3.org/TR/media-frags/#valid-uri-spatial the annotation must be within the bounds of the canvas.  The black borders are outside those bounds.

**Comment by radpet** [comment]
@beaudet What do you think? @rsinghal  What if someone wants to draw out of the bounds of an image as a side note?

**Comment by beaudet** [comment]
@radpet - we should follow the specs.  The trick will be to give the user clear visual cues that they cannot lay down a shape outside of the canvas.  Visually seeing the bounds of the canvas would probably be helpful or even changing the shape to be grayed out or the mouse turns to an X pointer when in an invalid region, etc.    Longer term, if the solution is to make the canvas bigger, maybe that could be added as part of the layers tab enhancement as outlined in #902.

**Comment by rsinghal** [comment]
Agreed, right now the image dimensions are the same as the canvas dimensions, which is why we can't draw outside of the bounds of the image.  But, it is perfectly valid to make the canvas dimensions bigger than the image, and then it would be valid to draw an annotation outside of the image bounds.  But, that does mean we need to make OSD work better in those circumstances.

**Comment by rsinghal** [comment]
@radpet Have you looked into this at all?  I have started looking into this a little bit, but don't want to go too far if you have already started work on it.

**Comment by radpet** [comment]
@rsinghal No I haven't started yet. However, I was thinking about setting the size of the canvas to be the same size as the osd canvas on line https://github.com/IIIF/mirador/blob/release2.1/js/src/annotations/osd-svg-overlay.js#L52. Can we get the proper size here and set it? We should also handle window resize.

**Comment by rsinghal** [comment]
Hmm, that's an interesting idea.  I will work on this tomorrow and try to come up with a couple of solutions.

**Comment by radpet** [comment]
@rsinghal I'll check it now and tell you in few minutes if it works

**Comment by radpet** [comment]
@rsinghal Edit:

This solution won't work the way I though because the currently the annotation and osd canvas have same dimensions. The approach that might work in my opinion is to set the canvas size to the current image bounds and resize accordingly when zoom event is fired.

**Comment by rsinghal** [comment]
In the old annotation work, I solved it by resetting the x,y coordinates for the rectangle as a user was dragging to make sure they were never outside of the image.  OSD normalizes the coordinates to be between 0 and 1 for x and 0 and 1/aspect ratio for y.  This is obviously more complex with the different types of shapes, but I think the logic still stands (https://github.com/IIIF/mirador/blob/master/js/src/annotations/osd-region-rect-tool.js#L175).  I will start with the rectangle tool since that is closest to the old annotation work.

**Comment by radpet** [comment]
You can try this solution directly to the osd-overlay.js because it propagetes the draw events down to each tool so you can implement some general solution if possible

**Comment by rsinghal** [comment]
@radpet If you look at `983-shapes-within-osd-viewer` you will see that when you draw a new shape, resize an existing shape, or move it, it keeps the shape within the bounds of the image.  

Except, when you draw an ellipse.  There is something weird in creating an ellipse that doesn't set points 5 and 9 as the right most and left most points, respectively (same with the top and bottom points).  Instead it uses 4 & 6 for the right most points.  But, if you resize an ellipse, it does use the correct points as the bounds, which prevents a user from resizing it outside of the image.  Can you take a look at how the original ellipse is being drawn and figure out why it's not using point 5 as the right most point (and for the other 3 "corners")? Thanks!

**Comment by radpet** [comment]
@rsinghal When you are creating you are basically resizing via point 6. Actually, when you resize via the 4,6 points it goes out of the canvas somehow.. I'll check your code and how the resizing is handled
