### ISSUE TITLE
Cannot create an annotation inside another annotation

### ISSUE THREAD

**Issue by gigamorph** [IIIF/mirador#987]
If I create the smaller/inner shape first I can create the bigger enclosing shape too. If I create the outer one first, however, clicking inside only selects the outer shape for moving around. 

<img width="367" alt="screen shot 2016-06-28 at 2 57 52 pm" src="https://cloud.githubusercontent.com/assets/86015/16428739/3b4ab27a-3d41-11e6-9e89-56a74377df0f.png">

Tried with https://github.com/IIIF/mirador/commit/0db6f1fdd26a13d3e66a108ba924ad68667a3561

**Comment by gigamorph** [comment]
1. Turn on "create" mode
1. Draw the larger rectangle (or any shape)
1. Fill in the annotation text and save
1. Try to draw another rectangle inside the existing one by clicking inside and dragging

Instead of the new shape appearing, the existing shape gets selected and moves with the mouse.

![ikyebb5lt5](https://cloud.githubusercontent.com/assets/86015/16431091/e7d08d34-3d4c-11e6-812c-8cd4f42bbb98.gif)

**Comment by rsinghal** [comment]
I'm not sure which build you are using, but it does not appear to be the latest in `release2.1` since you don't have some of the latest UI changes

**Comment by gigamorph** [comment]
I'm at 0db6f1fdd26a13d3e66a108ba924ad68667a3561

**Comment by gigamorph** [comment]
Nope, I didn't rebuild after pulling. You are right. My sincere apologies.
