### ISSUE TITLE
basic questions

### ISSUE THREAD

**Issue by selko** [IIIF/mirador#998]
Hi all!

Is it possible to open in mirador deep zoom images (.dzi). Normally i put like "image.tif.dzi" to open an image in other viewer.

How can i do to open my own images?

Kind regards!

**Comment by nicolasfranck** [comment]
Mirador expects the IIIF image api as protocol, so just putting a deepzoom link will not work.
IIP Image Server can work with DeepZoom images, and also understands the IIIF protocol:

http://iipimage.sourceforge.net/documentation/server/

For more information to put deepzoom images in IIIF protocol:

http://iipimage.sourceforge.net/2014/12/iiif/
